# -*- coding: utf-8 -*-
"""
Generador de contenido diario para Ángeles de Luz.
Genera el SQL con 30 días de contenido para cada uno de los 6 ángeles:
Gabriel, Rafael, Uriel, Chamuel, Zadkiel y Jophiel.

Uso: python scripts/generar_contenido.py
Salida: migrations/0006_contenido_otros_angeles.sql
"""

from datetime import date, timedelta
from pathlib import Path

# ============================================
# CONFIGURACIÓN
# ============================================

FECHA_INICIO = date(2026, 9, 23)
DIAS = 30

# ============================================
# CONTENIDO POR ÁNGEL
# ============================================
# Cada ángel tiene listas de 30 elementos:
# versiculos (tuplas texto+cita), oraciones, reflexiones, bendiciones.
# El script combina el día N con el elemento N de cada lista.

CONTENIDO = {
    "gabriel": {
        "versiculos": [
            ("No temas, María, porque has hallado gracia delante de Dios.", "Lucas 1:30"),
            ("He aquí la sierva del Señor; hágase conmigo conforme a tu palabra.", "Lucas 1:38"),
            ("Bendita tú entre las mujeres, y bendito el fruto de tu vientre.", "Lucas 1:42"),
            ("Y el ángel le dijo: No temas, Zacarías, porque tu oración ha sido oída.", "Lucas 1:13"),
            ("Y respondiendo el ángel, le dijo: El Espíritu Santo vendrá sobre ti.", "Lucas 1:35"),
            ("Y de repente fue con el ángel una multitud de las huestes celestiales.", "Lucas 2:13"),
            ("Porque nada hay imposible para Dios.", "Lucas 1:37"),
            ("Y el ángel les dijo: No temáis; porque he aquí os doy nuevas de gran gozo.", "Lucas 2:10"),
            ("Engrandece mi alma al Señor, y mi espíritu se regocija en Dios mi Salvador.", "Lucas 1:46-47"),
            ("Haced todo sin murmuraciones y contiendas.", "Filipenses 2:14"),
            ("Sea vuestro hablar: Sí, sí; no, no.", "Mateo 5:37"),
            ("La palabra de Cristo more en abundancia en vosotros.", "Colosenses 3:16"),
            ("Todo lo puedo en Cristo que me fortalece.", "Filipenses 4:13"),
            ("La lengua apacible es árbol de vida.", "Proverbios 15:4"),
            ("En las muchas palabras no falta pecado; mas el que refrena sus labios es prudente.", "Proverbios 10:19"),
            ("Porque por tus palabras serás justificado, y por tus palabras serás condenado.", "Mateo 12:37"),
            ("El hombre se alegra con la respuesta de su boca; y la palabra a su tiempo, ¡cuán buena es!", "Proverbios 15:23"),
            ("Sean gratos los dichos de mi boca y la meditación de mi corazón delante de ti.", "Salmo 19:14"),
            ("Manantial de vida es el entendimiento para el que lo posee.", "Proverbios 16:22"),
            ("El corazón del justo piensa para responder; mas la boca de los impíos derrama malas cosas.", "Proverbios 15:28"),
            ("Encomienda a Jehová tus obras, y tus pensamientos serán afirmados.", "Proverbios 16:3"),
            ("El que guarda su boca guarda su alma.", "Proverbios 13:3"),
            ("Porque la palabra de Dios es viva y eficaz.", "Hebreos 4:12"),
            ("La exposición de tus palabras alumbra; hace entender a los simples.", "Salmo 119:130"),
            ("Lámpara es a mis pies tu palabra, y lumbre a mi camino.", "Salmo 119:105"),
            ("Desead, como niños recién nacidos, la leche espiritual no adulterada.", "1 Pedro 2:2"),
            ("Toda Escritura es inspirada por Dios, y útil para enseñar.", "2 Timoteo 3:16"),
            ("Y conoceréis la verdad, y la verdad os hará libres.", "Juan 8:32"),
            ("El cielo y la tierra pasarán, pero mis palabras no pasarán.", "Mateo 24:35"),
            ("Y aquel Verbo fue hecho carne, y habitó entre nosotros.", "Juan 1:14"),
        ],
        "oraciones": [
            "San Gabriel, ayúdame a escuchar la voz de Dios con atención. Amén.",
            "San Gabriel, enséñame a confiar como María confió. Amén.",
            "San Gabriel, ayúdame a reconocer las bendiciones en mi vida. Amén.",
            "San Gabriel, mensajero divino, guíame en mis decisiones. Amén.",
            "San Gabriel, ayúdame a proclamar con valentía la verdad. Amén.",
            "San Gabriel, ilumina mi entendimiento con la luz del Espíritu. Amén.",
            "San Gabriel, enséñame a esperar con fe en las promesas de Dios. Amén.",
            "San Gabriel, ayúdame a decir 'sí' a lo que Dios me pide. Amén.",
            "San Gabriel, acompaña mi oración y preséntala ante el trono divino. Amén.",
            "San Gabriel, ayúdame a ser portador de buenas noticias. Amén.",
            "San Gabriel, enséñame a comunicar con amor y verdad. Amén.",
            "San Gabriel, cuida mi lengua y mis palabras. Amén.",
            "San Gabriel, ayúdame a escuchar antes de hablar. Amén.",
            "San Gabriel, guíame al silencio cuando sea necesario. Amén.",
            "San Gabriel, ayúdame a meditar la Palabra de Dios. Amén.",
            "San Gabriel, ilumina mi mente al leer las Escrituras. Amén.",
            "San Gabriel, enséñame a compartir la fe con alegría. Amén.",
            "San Gabriel, ayúdame a ser luz para quienes me rodean. Amén.",
            "San Gabriel, guíame en la verdad y en el bien. Amén.",
            "San Gabriel, ayúdame a decir no al mal y sí al bien. Amén.",
            "San Gabriel, custodia mi corazón y mis pensamientos. Amén.",
            "San Gabriel, ayúdame a discernir la voluntad de Dios. Amén.",
            "San Gabriel, enséñame a proclamar tu mensaje con humildad. Amén.",
            "San Gabriel, ayúdame a escuchar la voz de Dios en el silencio. Amén.",
            "San Gabriel, guíame en el camino de la fe. Amén.",
            "San Gabriel, ilumina mi camino con la Palabra divina. Amén.",
            "San Gabriel, enséñame a confiar en la providencia. Amén.",
            "San Gabriel, ayúdame a caminar en la verdad. Amén.",
            "San Gabriel, protégeme de la mentira y el engaño. Amén.",
            "San Gabriel, lleva mis plegarias hasta el trono de Dios. Amén.",
        ],
        "reflexiones": [
            "A veces Dios habla en susurros. Gabriel te enseña a escuchar con el corazón abierto.",
            "La confianza se construye día a día, en lo pequeño, en lo cotidiano. Hoy, un 'sí' más.",
            "Las bendiciones más grandes suelen estar escondidas en lo ordinario. Abre los ojos.",
            "Cada decisión es una oportunidad para alinearte con lo divino. No temas equivocarte.",
            "La verdad proclamada con amor transforma más que mil discursos vacíos.",
            "La luz del Espíritu ilumina los rincones que nosotros no podemos ver.",
            "Esperar en Dios no es pasividad, es confianza activa. Él está trabajando.",
            "Cada 'sí' a Dios es una puerta que se abre a algo más grande de lo que imaginamos.",
            "Tu oración no se pierde. Llega, aunque no veas el resultado inmediato.",
            "Ser portador de buenas noticias es uno de los regalos más grandes que puedes ofrecer.",
            "El amor y la verdad no están reñidos. Se necesitan mutuamente para florecer.",
            "Las palabras construyen o destruyen. Elige siempre las que sanan.",
            "Escuchar de verdad es un acto de amor. Hoy, escucha más de lo que hablas.",
            "El silencio no es vacío, es espacio donde Dios puede hablar.",
            "Meditar la Palabra es dejar que penetre hasta lo más profundo del ser.",
            "La Escritura es un pozo sin fondo. Cada día puedes sacar agua nueva.",
            "Compartir la fe no es imponer, es ofrecer. Hazlo con alegría.",
            "Tu luz, aunque pequeña, puede disipar muchas sombras a tu alrededor.",
            "Caminar en la verdad no siempre es fácil, pero siempre es liberador.",
            "Cada 'no' al mal es un 'sí' al bien. Elige bien hoy.",
            "El corazón y los pensamientos son la fuente de todo lo demás. Cuídalos.",
            "Discernir no es adivinar. Es escuchar, orar y esperar la paz interior.",
            "La humildad abre puertas que la arrogancia cierra para siempre.",
            "En el silencio profundo, Dios sigue hablando. ¿Le estás escuchando?",
            "El camino de la fe es un caminar diario, no un destino instantáneo.",
            "La Palabra ilumina incluso los senderos que parecen más oscuros.",
            "Confiar en la providencia es soltar el control y descansar en el amor.",
            "La verdad te hará libre, pero primero te invita a dejar atrás las cadenas.",
            "Protegerse del engaño empieza por conocer la Verdad que nos sostiene.",
            "Tu plegaria sube como incienso hasta el trono de Dios. Nunca se pierde.",
        ],
        "bendiciones": [
            "Que la claridad de San Gabriel ilumine tus decisiones.",
            "Que la fe de San Gabriel fortalezca tu alma.",
            "Que la gracia de San Gabriel te acompañe hoy.",
            "Que el mensaje de San Gabriel guíe tus pasos.",
            "Que la valentía de San Gabriel sostenga tu corazón.",
            "Que la luz del Espíritu te envuelva hoy.",
            "Que la esperanza de San Gabriel anime tu camino.",
            "Que tu 'sí' a Dios abra puertas de bendición.",
            "Que tu oración llegue al cielo y regrese en paz.",
            "Que seas portador de buenas noticias donde vayas.",
            "Que tus palabras sean bálsamo para quienes te escuchan.",
            "Que el amor y la verdad guíen cada palabra tuya.",
            "Que escuches más de lo que hablas y aprendas en el silencio.",
            "Que el silencio te regale la voz de Dios.",
            "Que la Palabra de Dios habite abundantemente en ti.",
            "Que la Escritura sea lámpara a tus pies.",
            "Que tu fe se comparta con alegría y sencillez.",
            "Que tu luz brille sin miedo en la oscuridad.",
            "Que camines siempre en la verdad y el bien.",
            "Que sepas decir no al mal y sí al bien.",
            "Que tu corazón y mente estén custodiados por Gabriel.",
            "Que sepas discernir la voz de Dios en tu vida.",
            "Que tu humildad abra puertas de bendición.",
            "Que en el silencio encuentres respuestas y consuelo.",
            "Que tu caminar en la fe sea firme y gozoso.",
            "Que la Palabra ilumine cada decisión de tu día.",
            "Que la providencia divina sostenga tus pasos.",
            "Que la verdad te libre de toda esclavitud interior.",
            "Que la protección de Gabriel te guarde de todo engaño.",
            "Que tus plegarias sean escuchadas y respondidas en paz.",
        ],
    },

    # ============================================
    # RAFAEL — Sanación, viajes, matrimonio
    # ============================================
    "rafael": {
        "versiculos": [
            ("Yo soy Jehová tu sanador.", "Éxodo 15:26"),
            ("Sáname, oh Jehová, y seré sano; sálvame, y seré salvo.", "Jeremías 17:14"),
            ("El Señor sostiene al que tropieza y levanta al que está caído.", "Salmo 145:14"),
            ("Jehová es mi fortaleza y mi escudo; en él confió mi corazón.", "Salmo 28:7"),
            ("Él sana a los quebrantados de corazón, y venda sus heridas.", "Salmo 147:3"),
            ("Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios.", "Salmo 103:2"),
            ("Envió su palabra, y los sanó, y los libró de su ruina.", "Salmo 107:20"),
            ("Porque yo te restauraré y sanaré tus heridas, dice Jehová.", "Jeremías 30:17"),
            ("Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", "Mateo 11:28"),
            ("Y la oración de fe salvará al enfermo, y el Señor lo levantará.", "Santiago 5:15"),
            ("Jehová te guardará de todo mal; guardará tu alma.", "Salmo 121:7"),
            ("Porque a sus ángeles mandará acerca de ti, que te guarden en todos tus caminos.", "Salmo 91:11"),
            ("Jehová guardará tu salida y tu entrada desde ahora y para siempre.", "Salmo 121:8"),
            ("El ángel de Jehová acampa alrededor de los que le temen, y los defiende.", "Salmo 34:7"),
            ("He aquí yo envío mi ángel delante de ti, para que te guarde en el camino.", "Éxodo 23:20"),
            ("Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.", "Salmo 46:1"),
            ("En paz me acostaré, y asimismo dormiré; porque solo tú, Jehová, me haces vivir confiado.", "Salmo 4:8"),
            ("Jehová es mi pastor; nada me faltará.", "Salmo 23:1"),
            ("El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", "Salmo 91:1"),
            ("Porque él te librará del lazo del cazador, de la peste destructora.", "Salmo 91:3"),
            ("El matrimonio sea honroso en todos, y el lecho sin mancilla.", "Hebreos 13:4"),
            ("Y los dos serán una sola carne; así que no son ya más dos, sino una sola carne.", "Marcos 10:8"),
            ("El que halla esposa halla el bien, y alcanza la benevolencia de Jehová.", "Proverbios 18:22"),
            ("Sobre todo, vestíos de amor, que es el vínculo perfecto.", "Colosenses 3:14"),
            ("El amor es sufrido, es benigno; el amor no tiene envidia.", "1 Corintios 13:4"),
            ("Y sobre todas estas cosas vestíos de amor, que es el vínculo perfecto.", "Colosenses 3:14"),
            ("Regocijaos en el Señor siempre. Y otra vez os digo: ¡Regocijaos!", "Filipenses 4:4"),
            ("Gozaos con los que se gozan; llorad con los que lloran.", "Romanos 12:15"),
            ("Sobrellevad los unos las cargas de los otros, y cumplid así la ley de Cristo.", "Gálatas 6:2"),
            ("Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros.", "Efesios 4:32"),
        ],
        "oraciones": [
            "San Rafael, medicina de Dios, sáname en cuerpo, alma y espíritu. Amén.",
            "San Rafael, acompaña mis pasos en este viaje de la vida. Amén.",
            "San Rafael, protege mi matrimonio y mi familia. Amén.",
            "San Rafael, alivia mis dolencias y renueva mis fuerzas. Amén.",
            "San Rafael, acompaña a los que sufren y consuela sus corazones. Amén.",
            "San Rafael, ayúdame a aceptar lo que no puedo cambiar. Amén.",
            "San Rafael, restaura mi salud y mi esperanza. Amén.",
            "San Rafael, guárdame en todos mis caminos. Amén.",
            "San Rafael, sé mi compañero en la enfermedad y en la salud. Amén.",
            "San Rafael, ayúdame a descansar en Dios. Amén.",
            "San Rafael, custodia a mis seres queridos. Amén.",
            "San Rafael, protégeme de todo peligro. Amén.",
            "San Rafael, acompaña a los viajeros y a los peregrinos. Amén.",
            "San Rafael, guarda mi hogar y mis bienes. Amén.",
            "San Rafael, ayúdame a confiar en la providencia. Amén.",
            "San Rafael, sé mi guía en tierras desconocidas. Amén.",
            "San Rafael, dame serenidad en la incertidumbre. Amén.",
            "San Rafael, enséñame a cuidar mi cuerpo como templo del Espíritu. Amén.",
            "San Rafael, sana las heridas de mi pasado. Amén.",
            "San Rafael, líbrame de toda enfermedad. Amén.",
            "San Rafael, bendice mi matrimonio y mi hogar. Amén.",
            "San Rafael, une lo que está dividido. Amén.",
            "San Rafael, fortalece mi amor por los míos. Amén.",
            "San Rafael, enséñame a amar como Dios ama. Amén.",
            "San Rafael, ayúdame a perdonar y a pedir perdón. Amén.",
            "San Rafael, trae paz a mi familia. Amén.",
            "San Rafael, sé el vínculo de unión en mi hogar. Amén.",
            "San Rafael, ayúdame a llevar las cargas de los demás. Amén.",
            "San Rafael, consuela a los que lloran. Amén.",
            "San Rafael, guárdame y guía a los que amo. Amén.",
        ],
        "reflexiones": [
            "La sanación no siempre es física. A veces Dios sana el alma antes que el cuerpo.",
            "Cada viaje es una oportunidad para encontrarte con Dios en lo desconocido.",
            "El matrimonio es un camino de santidad, no de perfección. Se construye día a día.",
            "El dolor no es el final, es una puerta a algo nuevo que Dios está gestando.",
            "Acompañar al que sufre es una de las formas más puras de amor.",
            "Aceptar lo que no podemos cambiar es el primer paso hacia la paz.",
            "La salud es un regalo; cuidarla es un acto de gratitud.",
            "En cada camino, Dios envía ángeles que te guardan. Confía.",
            "La enfermedad puede ser maestra de humildad y paciencia.",
            "El descanso no es debilidad, es confianza en que Dios sostiene.",
            "Custodiar a los que amas es una forma de oración continua.",
            "Los peligros existen, pero la protección divina es más grande.",
            "Los viajeros llevan consigo la presencia de Dios y la compañía de los ángeles.",
            "Tu hogar puede ser un pequeño cielo si lo llenas de amor.",
            "La providencia no siempre nos da lo que queremos, pero sí lo que necesitamos.",
            "En tierras desconocidas, Dios sigue siendo conocido y cercano.",
            "La incertidumbre es el terreno donde crece la fe.",
            "Tu cuerpo es templo del Espíritu. Cuídalo con reverencia.",
            "El pasado puede sanar cuando lo ponemos en manos de Dios.",
            "La enfermedad no tiene la última palabra. La vida sí.",
            "El matrimonio es un espejo donde aprendes a amar mejor cada día.",
            "Unir lo dividido es una de las obras más hermosas del amor.",
            "El amor por los tuyos se demuestra en lo cotidiano, no solo en lo grande.",
            "Amar como Dios ama es el proyecto de toda una vida.",
            "Perdonar libera al que perdona más que al perdonado.",
            "La paz familiar es un tesoro que se construye con paciencia.",
            "El vínculo del amor es más fuerte que cualquier dificultad.",
            "Llevar las cargas de otros es cumplir la ley de Cristo.",
            "Consolar al que llora es prestar tu corazón como refugio.",
            "Guardar y guiar a los que amas es una de las misiones más sagradas.",
        ],
        "bendiciones": [
            "Que la sanación de San Rafael llegue a tu cuerpo y alma.",
            "Que San Rafael acompañe cada paso de tu camino.",
            "Que la bendición de San Rafael proteja tu hogar.",
            "Que la salud y la paz sean tus compañeras hoy.",
            "Que San Rafael consuele todo dolor que lleves dentro.",
            "Que aceptes con paz lo que no puedes cambiar.",
            "Que la salud florezca en ti como un regalo divino.",
            "Que los ángeles te guarden en todos tus caminos.",
            "Que en la enfermedad o en la salud, Dios te sostenga.",
            "Que el descanso repare tus fuerzas y tu alma.",
            "Que tus seres queridos estén siempre custodiados.",
            "Que la protección divina te envuelva hoy.",
            "Que San Rafael guíe tus viajes y tus pasos.",
            "Que tu hogar sea un refugio de paz y amor.",
            "Que la providencia divina sostenga cada día tu vida.",
            "Que en lo desconocido encuentres la cercanía de Dios.",
            "Que la serenidad te acompañe en la incertidumbre.",
            "Que cuides tu cuerpo como templo del Espíritu.",
            "Que las heridas del pasado sanen con el tiempo.",
            "Que la enfermedad no te robe la esperanza.",
            "Que tu matrimonio sea bendecido y fortalecido.",
            "Que el amor una lo que estaba dividido.",
            "Que el amor por los tuyos crezca cada día.",
            "Que aprendas a amar como Dios te ama a ti.",
            "Que el perdón libere tu corazón de toda carga.",
            "Que la paz reine en tu familia y en tu hogar.",
            "Que el vínculo del amor sea siempre tu fortaleza.",
            "Que lleves con amor las cargas de los demás.",
            "Que tus consuelos sean bálsamo para quien llora.",
            "Que San Rafael te guarde y guíe a los que amas.",
        ],
    },

    # ============================================
    # URIEL — Sabiduría, luz, conocimiento
    # ============================================
    "uriel": {
        "versiculos": [
            ("Lámpara es a mis pies tu palabra, y lumbre a mi camino.", "Salmo 119:105"),
            ("El principio de la sabiduría es el temor de Jehová.", "Proverbios 9:10"),
            ("Si alguno tiene falta de sabiduría, pídala a Dios, el cual da a todos abundantemente.", "Santiago 1:5"),
            ("En el entendimiento del hombre está la fuente de la vida.", "Proverbios 16:22"),
            ("La exposición de tus palabras alumbra; hace entender a los simples.", "Salmo 119:130"),
            ("Dame entendimiento, y guardaré tu ley, y la cumpliré de todo corazón.", "Salmo 119:34"),
            ("El que adquiere entendimiento ama su alma.", "Proverbios 19:8"),
            ("Mas la sabiduría que es de lo alto es primeramente pura, después pacífica.", "Santiago 3:17"),
            ("El corazón del entendido adquiere sabiduría.", "Proverbios 18:15"),
            ("Porque Jehová da la sabiduría, y de su boca viene el conocimiento.", "Proverbios 2:6"),
            ("Mejor es adquirir sabiduría que oro preciado.", "Proverbios 16:16"),
            ("Bienaventurado el hombre que halla la sabiduría.", "Proverbios 3:13"),
            ("El entendido en la palabra hallará el bien.", "Proverbios 16:20"),
            ("La sabiduría es lo primero; adquiere sabiduría.", "Proverbios 4:7"),
            ("El que anda con sabios, sabio será.", "Proverbios 13:20"),
            ("Andad como hijos de luz, porque el fruto del Espíritu es en toda bondad.", "Efesios 5:8-9"),
            ("Vosotros sois la luz del mundo.", "Mateo 5:14"),
            ("Así alumbre vuestra luz delante de los hombres.", "Mateo 5:16"),
            ("Dios es luz, y no hay ningunas tinieblas en él.", "1 Juan 1:5"),
            ("Todo lo que es verdadero, todo lo honesto, todo lo justo, en esto pensad.", "Filipenses 4:8"),
            ("Escudriñad las Escrituras; porque a vosotros os parece que en ellas tenéis la vida eterna.", "Juan 5:39"),
            ("Y conoceréis la verdad, y la verdad os hará libres.", "Juan 8:32"),
            ("La palabra de Cristo more en abundancia en vosotros.", "Colosenses 3:16"),
            ("Toda Escritura es inspirada por Dios, y útil para enseñar.", "2 Timoteo 3:16"),
            ("Porque la palabra de Dios es viva y eficaz.", "Hebreos 4:12"),
            ("Desead, como niños recién nacidos, la leche espiritual no adulterada.", "1 Pedro 2:2"),
            ("El cielo y la tierra pasarán, pero mis palabras no pasarán.", "Mateo 24:35"),
            ("Y aquel Verbo fue hecho carne, y habitó entre nosotros.", "Juan 1:14"),
            ("En él estaba la vida, y la vida era la luz de los hombres.", "Juan 1:4"),
            ("La luz en las tinieblas resplandece, y las tinieblas no prevalecieron contra ella.", "Juan 1:5"),
        ],
        "oraciones": [
            "Uriel, luz divina, ilumina mi mente y mi entendimiento. Amén.",
            "Uriel, guíame en el camino del conocimiento y la verdad. Amén.",
            "Uriel, ayúdame a estudiar con dedicación y sabiduría. Amén.",
            "Uriel, inspira mis pensamientos y mis proyectos. Amén.",
            "Uriel, ilumina las decisiones que debo tomar hoy. Amén.",
            "Uriel, ayúdame a buscar la verdad con humildad. Amén.",
            "Uriel, dame sabiduría para entender las Escrituras. Amén.",
            "Uriel, guíame en el estudio de tu Palabra. Amén.",
            "Uriel, ilumina mi mente en la confusión. Amén.",
            "Uriel, ayúdame a discernir lo verdadero de lo falso. Amén.",
            "Uriel, enséñame a pensar en lo bueno y lo justo. Amén.",
            "Uriel, guíame a la verdad que libera. Amén.",
            "Uriel, ilumina mi camino en la oscuridad. Amén.",
            "Uriel, ayúdame a aprender con alegría. Amén.",
            "Uriel, dame paciencia en el estudio y la investigación. Amén.",
            "Uriel, inspira mis palabras cuando enseño. Amén.",
            "Uriel, ayúdame a comprender la voluntad de Dios. Amén.",
            "Uriel, ilumina mi corazón para amar la verdad. Amén.",
            "Uriel, guíame al conocimiento que acerca a Dios. Amén.",
            "Uriel, ayúdame a crecer en sabiduría cada día. Amén.",
            "Uriel, ilumina mi entendimiento con tu luz. Amén.",
            "Uriel, enséñame a escuchar antes de juzgar. Amén.",
            "Uriel, guíame a la humildad intelectual. Amén.",
            "Uriel, ayúdame a reconocer mis limitaciones. Amén.",
            "Uriel, ilumina mi mente para servir mejor. Amén.",
            "Uriel, ayúdame a usar el conocimiento para el bien. Amén.",
            "Uriel, guíame a la verdad que transforma. Amén.",
            "Uriel, ilumina mis decisiones cotidianas. Amén.",
            "Uriel, enséñame a aprender de mis errores. Amén.",
            "Uriel, guíame siempre hacia la luz de Dios. Amén.",
        ],
        "reflexiones": [
            "La verdadera sabiduría empieza por reconocer cuánto no sabemos todavía.",
            "La luz de Dios ilumina los rincones más oscuros de nuestra mente.",
            "Estudiar es un acto de amor cuando se hace para servir mejor.",
            "Los pensamientos buenos son semillas de acciones buenas.",
            "Cada decisión iluminada por la fe es un paso hacia la plenitud.",
            "Buscar la verdad con humildad es más sabio que creer tenerla toda.",
            "Las Escrituras son un pozo sin fondo del que siempre se puede sacar agua nueva.",
            "En la confusión, la oración es la brújula que orienta.",
            "Discernir no es adivinar, es escuchar con atención y orar con paciencia.",
            "Pensar en lo bueno, lo justo y lo verdadero transforma la mente.",
            "La verdad que libera no siempre es cómoda, pero siempre es liberadora.",
            "En la oscuridad, incluso una pequeña luz marca la diferencia.",
            "Aprender con alegría es uno de los mayores regalos que puedes darte.",
            "La paciencia en el estudio es una forma de respeto hacia el conocimiento.",
            "Enseñar bien es un acto de generosidad y de humildad.",
            "Comprender la voluntad de Dios es un camino, no un destino.",
            "Amar la verdad es amar a Dios, porque Él es la Verdad.",
            "Todo conocimiento que acerca a Dios es conocimiento que vale la pena.",
            "Crecer en sabiduría es crecer en humanidad.",
            "La luz de Dios disipa toda oscuridad, si se la dejamos entrar.",
            "Escuchar antes de juzgar es uno de los gestos más sabios.",
            "La humildad intelectual es reconocer que siempre hay más por aprender.",
            "Conocer nuestros límites es el primer paso para superarlos.",
            "El conocimiento que no sirve al bien, no es verdadero conocimiento.",
            "Usar lo que sabes para ayudar a otros es sabiduría en acción.",
            "La verdad que transforma no es la que se acumula, sino la que se vive.",
            "Las decisiones pequeñas también merecen luz y discernimiento.",
            "Equivocarse es parte del aprendizaje; levantarse, parte del crecimiento.",
            "Caminar hacia la luz es caminar hacia Dios.",
            "La verdadera luz no deslumbra, ilumina con serenidad.",
        ],
        "bendiciones": [
            "Que la luz de Uriel ilumine tu mente y tu camino.",
            "Que la sabiduría de lo alto guíe tus decisiones.",
            "Que el estudio sea fuente de alegría y crecimiento.",
            "Que la inspiración de Uriel anime tus proyectos.",
            "Que ilumine tus decisiones y disipe tus dudas.",
            "Que busques la verdad con humildad y perseverancia.",
            "Que las Escrituras iluminen cada día tu vida.",
            "Que el estudio de la Palabra te transforme.",
            "Que en la confusión encuentres la luz de Dios.",
            "Que disciernas con claridad lo verdadero de lo falso.",
            "Que tus pensamientos se eleven a lo bueno y lo justo.",
            "Que la verdad de Dios te haga libre.",
            "Que la luz de Uriel disipe tus tinieblas.",
            "Que aprendas con alegría y enseñes con generosidad.",
            "Que la paciencia sea tu compañera en el estudio.",
            "Que tus enseñanzas inspiren a otros.",
            "Que comprendas la voluntad de Dios para tu vida.",
            "Que tu corazón ame la verdad cada día más.",
            "Que el conocimiento te acerque a Dios.",
            "Que crezcas en sabiduría y en gracia.",
            "Que la luz de Uriel ilumine tu entendimiento.",
            "Que sepas escuchar antes de juzgar.",
            "Que la humildad guíe tu camino intelectual.",
            "Que reconozcas tus límites con paz.",
            "Que tu mente iluminada sirva al bien común.",
            "Que uses el conocimiento para el bien de los demás.",
            "Que la verdad transforme tu vida desde dentro.",
            "Que ilumines cada decisión con discernimiento.",
            "Que aprendas de cada error y sigas creciendo.",
            "Que Uriel te guíe siempre hacia la luz de Dios.",
        ],
    },

    # ============================================
    # CHAMUEL — Paz, amor, búsqueda
    # ============================================
    "chamuel": {
        "versiculos": [
            ("La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da.", "Juan 14:27"),
            ("Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones.", "Filipenses 4:7"),
            ("Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios.", "Mateo 5:9"),
            ("Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad.", "Gálatas 5:22"),
            ("Seguid la paz con todos, y la santidad, sin la cual nadie verá al Señor.", "Hebreos 12:14"),
            ("Porque Dios no es Dios de confusión, sino de paz.", "1 Corintios 14:33"),
            ("En paz me acostaré, y asimismo dormiré; porque solo tú, Jehová, me haces vivir confiado.", "Salmo 4:8"),
            ("Mucha paz tienen los que aman tu ley, y no hay para ellos tropiezo.", "Salmo 119:165"),
            ("La misericordia y la verdad se encontraron; la justicia y la paz se besaron.", "Salmo 85:10"),
            ("Amarás a tu prójimo como a ti mismo.", "Mateo 22:39"),
            ("Un mandamiento nuevo os doy: Que os améis unos a otros.", "Juan 13:34"),
            ("El amor es sufrido, es benigno; el amor no tiene envidia.", "1 Corintios 13:4"),
            ("Sobre todo, vestíos de amor, que es el vínculo perfecto.", "Colosenses 3:14"),
            ("Amados, amémonos unos a otros; porque el amor es de Dios.", "1 Juan 4:7"),
            ("Nosotros le amamos a él, porque él nos amó primero.", "1 Juan 4:19"),
            ("Buscad la paz, y seguidla.", "1 Pedro 3:11"),
            ("Si es posible, en cuanto dependa de vosotros, estad en paz con todos.", "Romanos 12:18"),
            ("El que ama a su hermano, permanece en la luz.", "1 Juan 2:10"),
            ("Bienaventurados los que buscan la paz y la procuran.", "Proverbios 12:20"),
            ("Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros.", "Efesios 4:32"),
            ("No os ha sobrevenido ninguna tentación que no sea humana.", "1 Corintios 10:13"),
            ("Buscad, y hallaréis; llamad, y se os abrirá.", "Mateo 7:7"),
            ("Porque todo aquel que pide, recibe; y el que busca, halla.", "Mateo 7:8"),
            ("Jehová es mi pastor; nada me faltará.", "Salmo 23:1"),
            ("Esforzaos, y él fortalecerá vuestro corazón, todos los que esperáis en Jehová.", "Salmo 31:24"),
            ("Cercano está Jehová a todos los que le invocan de veras.", "Salmo 145:18"),
            ("Encomienda a Jehová tu camino, y confía en él; y él hará.", "Salmo 37:5"),
            ("El corazón alegre constituye buen remedio.", "Proverbios 17:22"),
            ("Regocijaos en el Señor siempre. Y otra vez os digo: ¡Regocijaos!", "Filipenses 4:4"),
            ("Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios.", "Filipenses 4:6"),
        ],
        "oraciones": [
            "Chamuel, trae paz a mi corazón y a mi mente. Amén.",
            "Chamuel, ayúdame a amar como Dios me ama. Amén.",
            "Chamuel, enséñame a perdonar de corazón. Amén.",
            "Chamuel, trae serenidad a mis días agitados. Amén.",
            "Chamuel, ayúdame a encontrar lo que he perdido. Amén.",
            "Chamuel, guíame hacia las personas que necesitan paz. Amén.",
            "Chamuel, dame tu paz en medio de la tormenta. Amén.",
            "Chamuel, sana las relaciones rotas en mi vida. Amén.",
            "Chamuel, ayúdame a ser un pacificador. Amén.",
            "Chamuel, trae armonía a mi hogar. Amén.",
            "Chamuel, enséñame a amar sin condiciones. Amén.",
            "Chamuel, ayúdame a dejar atrás el rencor. Amén.",
            "Chamuel, dame paz cuando la ansiedad me invade. Amén.",
            "Chamuel, guíame a la reconciliación. Amém.",
            "Chamuel, trae paz a mis pensamientos. Amén.",
            "Chamuel, ayúdame a buscar la paz y seguirla. Amén.",
            "Chamuel, dame serenidad ante las dificultades. Amén.",
            "Chamuel, ayúdame a amar a quien me cuesta amar. Amén.",
            "Chamuel, sana mi corazón herido. Amén.",
            "Chamuel, trae paz a las naciones y al mundo. Amén.",
            "Chamuel, ayúdame a encontrar el gozo en lo simple. Amén.",
            "Chamuel, guíame en la búsqueda de lo que anhelo. Amén.",
            "Chamuel, ayúdame a confiar en el tiempo de Dios. Amén.",
            "Chamuel, trae esperanza a mi vida. Amén.",
            "Chamuel, dame paz en la espera. Amén.",
            "Chamuel, ayúdame a vivir en paz con todos. Amén.",
            "Chamuel, enséñame a perdonarme a mí mismo. Amén.",
            "Chamuel, trae reconciliación a mi familia. Amén.",
            "Chamuel, ayúdame a encontrar la paz interior. Amén.",
            "Chamuel, guíame siempre hacia el amor y la paz. Amén.",
        ],
        "reflexiones": [
            "La paz no es ausencia de problemas, sino presencia de Dios en medio de ellos.",
            "El amor verdadero se demuestra en lo cotidiano, no solo en lo extraordinario.",
            "Perdonar no es olvidar, es soltar el peso que te ata al pasado.",
            "La serenidad no viene de fuera, viene de dentro. Cultívala cada día.",
            "A veces lo que perdemos nos prepara para encontrar algo mejor.",
            "Ser pacificador no es evitar conflictos, es resolverlos con amor.",
            "La paz empieza en tu interior y se refleja en lo exterior.",
            "Las relaciones rotas pueden sanar con paciencia y perdón.",
            "El amor sin condiciones es el más puro y el más transformador.",
            "Soltar el rencor es un regalo que te haces a ti mismo.",
            "La ansiedad se calma cuando dejamos de intentar controlarlo todo.",
            "Reconciliarse es un acto de valentía y de humildad.",
            "Los pensamientos en paz generan días en paz.",
            "Buscar la paz es una decisión diaria, no un estado permanente.",
            "La serenidad ante las dificultades es señal de fe madura.",
            "Amar a quien nos cuesta amar es el mayor acto de libertad.",
            "El corazón herido puede sanar; el tiempo y el amor son medicina.",
            "La paz del mundo empieza por la paz de cada corazón.",
            "El gozo está en las cosas simples; solo hay que aprender a verlo.",
            "Buscar con fe es encontrar con sorpresa.",
            "El tiempo de Dios no es el nuestro, pero siempre es el mejor.",
            "La esperanza es la luz que ilumina incluso la noche más oscura.",
            "En la espera, Dios trabaja silenciosamente a nuestro favor.",
            "Vivir en paz con todos es un proyecto de toda la vida.",
            "Perdonarse a uno mismo es tan importante como perdonar a otros.",
            "La reconciliación familiar es un regalo que trasciende generaciones.",
            "La paz interior es un tesoro que nadie te puede arrebatar.",
            "El amor y la paz son las alas del alma.",
            "Cuando buscas la paz, la encuentras; cuando la siembras, florece.",
            "El camino del amor es el camino de la paz.",
        ],
        "bendiciones": [
            "Que la paz de Chamuel inunde tu corazón.",
            "Que aprendas a amar como Dios te ama.",
            "Que el perdón libere tu alma de toda carga.",
            "Que la serenidad te acompañe en cada día.",
            "Que encuentres lo que tu corazón busca.",
            "Que seas instrumento de paz donde vayas.",
            "Que la paz de Dios guarde tu mente y corazón.",
            "Que las relaciones rotas sanen en tu vida.",
            "Que seas un pacificador en tu entorno.",
            "Que la armonía reine en tu hogar.",
            "Que ames sin condiciones y sin medida.",
            "Que dejes atrás el rencor y abraces la paz.",
            "Que la ansiedad se disipe ante la presencia de Dios.",
            "Que la reconciliación sea posible en tu vida.",
            "Que tus pensamientos estén en paz.",
            "Que busques y sigas siempre la paz.",
            "Que la serenidad sea tu compañera en las dificultades.",
            "Que ames incluso a quien te cuesta amar.",
            "Que tu corazón herido encuentre sanación.",
            "Que la paz reine en tu entorno y en el mundo.",
            "Que el gozo de lo simple llene tus días.",
            "Que encuentres lo que anhelas con fe y paciencia.",
            "Que confíes en el tiempo perfecto de Dios.",
            "Que la esperanza ilumine tu camino.",
            "Que la paz te sostenga en la espera.",
            "Que vivas en paz con todos y contigo mismo.",
            "Que aprendas a perdonarte y a seguir adelante.",
            "Que la reconciliación llegue a tu familia.",
            "Que la paz interior sea tu fuerza cada día.",
            "Que Chamuel te guíe siempre hacia el amor y la paz.",
        ],
    },

    # ============================================
    # ZADKIEL — Perdón, misericordia, transformación
    # ============================================
    "zadkiel": {
        "versiculos": [
            ("Jehová es misericordioso y piadoso; tardo para la ira, y grande en misericordia.", "Salmo 145:8"),
            ("Como el padre se compadece de sus hijos, se compadece Jehová de los que le temen.", "Salmo 103:13"),
            ("Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros.", "Efesios 4:32"),
            ("Porque si perdonáis a los hombres sus ofensas, os perdonará también a vosotros vuestro Padre celestial.", "Mateo 6:14"),
            ("Y cuando estéis orando, perdonad, si tenéis algo contra alguno.", "Marcos 11:25"),
            ("De manera que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron.", "2 Corintios 5:17"),
            ("He aquí que yo hago cosa nueva; pronto saldrá a luz; ¿no la conoceréis?", "Isaías 43:19"),
            ("Echad de vosotros todas vuestras transgresiones con que habéis pecado.", "Ezequiel 18:31"),
            ("Lávame más y más de mi maldad, y límpiame de mi pecado.", "Salmo 51:2"),
            ("Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.", "Salmo 51:10"),
            ("Vuélvete a mí, y yo me volveré a ti.", "Malaquías 3:7"),
            ("Desecha todas tus transgresiones, y hazte un corazón nuevo.", "Ezequiel 18:31"),
            ("Jehová está cerca de los quebrantados de corazón.", "Salmo 34:18"),
            ("No te acordarás de las cosas anteriores, ni las traerás a la memoria.", "Isaías 65:17"),
            ("Yo, yo soy el que borro tus rebeliones por amor de mí mismo.", "Isaías 43:25"),
            ("Sáname, oh Jehová, y seré sano; sálvame, y seré salvo.", "Jeremías 17:14"),
            ("Porque yo sé los pensamientos que tengo acerca de vosotros, pensamientos de paz.", "Jeremías 29:11"),
            ("El amor cubrirá multitud de pecados.", "1 Pedro 4:8"),
            ("Antes bien, sed benignos unos con otros, misericordiosos, perdonándoos unos a otros.", "Efesios 4:32"),
            ("Porque yo perdonaré sus iniquidades, y nunca más me acordaré de sus pecados.", "Jeremías 31:34"),
            ("Nunca más se acordará el pecado ni la iniquidad.", "Hebreos 10:17"),
            ("Confesaos vuestras ofensas unos a otros, y orad unos por otros.", "Santiago 5:16"),
            ("Si confesamos nuestros pecados, él es fiel y justo para perdonar.", "1 Juan 1:9"),
            ("Todos pecaron, y están destituidos de la gloria de Dios.", "Romanos 3:23"),
            ("Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros.", "Romanos 5:8"),
            ("Y todo lo que antes era ganancia, lo tengo por basura, a fin de ganar a Cristo.", "Filipenses 3:7-8"),
            ("Olvidando ciertamente lo que queda atrás, y extendiéndome a lo que está delante.", "Filipenses 3:13"),
            ("Consideraos muertos al pecado, pero vivos para Dios en Cristo Jesús.", "Romanos 6:11"),
            ("De modo que ya no eres esclavo, sino hijo.", "Gálatas 4:7"),
            ("La misericordia y la verdad se encontraron; la justicia y la paz se besaron.", "Salmo 85:10"),
        ],
        "oraciones": [
            "Zadkiel, enséñame a perdonar como Dios me perdona. Amén.",
            "Zadkiel, ayúdame a soltar el rencor y el resentimiento. Amén.",
            "Zadkiel, transforma mi corazón endurecido. Amén.",
            "Zadkiel, ayúdame a pedir perdón a quien he ofendido. Amén.",
            "Zadkiel, dame un corazón misericordioso. Amén.",
            "Zadkiel, ayúdame a perdonarme a mí mismo. Amén.",
            "Zadkiel, límpiame de toda culpa y remordimiento. Amén.",
            "Zadkiel, renueva mi espíritu y mi mente. Amén.",
            "Zadkiel, ayúdame a dejar atrás el pasado. Amén.",
            "Zadkiel, dame fuerzas para comenzar de nuevo. Amén.",
            "Zadkiel, transforma mi dolor en aprendizaje. Amén.",
            "Zadkiel, ayúdame a ver con ojos nuevos. Amén.",
            "Zadkiel, sana las heridas de mi alma. Amén.",
            "Zadkiel, ayúdame a aceptar el perdón de Dios. Amén.",
            "Zadkiel, dame humildad para reconocer mis errores. Amén.",
            "Zadkiel, ayúdame a perdonar sin condiciones. Amén.",
            "Zadkiel, transforma mis pensamientos negativos. Amén.",
            "Zadkiel, ayúdame a vivir en la libertad de los hijos de Dios. Amén.",
            "Zadkiel, dame un corazón nuevo y un espíritu renovado. Amén.",
            "Zadkiel, ayúdame a olvidar lo que debe ser olvidado. Amén.",
            "Zadkiel, transforma mi vida desde dentro. Amén.",
            "Zadkiel, ayúdame a levantarme después de caer. Amén.",
            "Zadkiel, dame valor para cambiar. Amén.",
            "Zadkiel, ayúdame a caminar en novedad de vida. Amén.",
            "Zadkiel, transforma mis debilidades en fortalezas. Amén.",
            "Zadkiel, ayúdame a perdonar y a seguir adelante. Amén.",
            "Zadkiel, dame paz con mi pasado. Amén.",
            "Zadkiel, ayúdame a crecer a través del dolor. Amén.",
            "Zadkiel, transforma mi corazón como solo Dios puede. Amén.",
            "Zadkiel, guíame siempre hacia la misericordia y el perdón. Amén.",
        ],
        "reflexiones": [
            "El perdón no cambia el pasado, pero sí cambia el futuro.",
            "Perdonar no es decir que estuvo bien, es liberarte del peso del rencor.",
            "La misericordia es un regalo que se multiplica cuando se comparte.",
            "Transformarse no es cambiar de piel, es cambiar de corazón.",
            "Dios no se cansa de perdonar; nosotros no deberíamos cansarnos de pedir perdón.",
            "El pasado no puede cambiarse, pero sí puede soltarse.",
            "La culpa que te atormenta no viene de Dios; Él perdona sin condiciones.",
            "Reconocer los errores es el primer paso de la transformación.",
            "Cuando perdonas, liberas a dos: al otro y a ti mismo.",
            "La misericordia no es debilidad, es la fuerza más poderosa del universo.",
            "Cada nuevo día es una oportunidad para empezar de nuevo.",
            "Dios ve en ti lo que puedes llegar a ser, no solo lo que has sido.",
            "Transformarse duele a veces, pero siempre vale la pena.",
            "El corazón endurecido se ablanda con el calor del amor divino.",
            "Perdonarse a sí mismo es un acto de humildad y de fe.",
            "La verdadera libertad se encuentra al soltar el rencor.",
            "Dios no recuerda tus pecados una vez perdonados. ¿Por qué los recuerdas tú?",
            "La transformación empieza en lo pequeño y se extiende a lo grande.",
            "El dolor puede ser maestro de sabiduría si se vive con fe.",
            "Cada caída es una oportunidad para levantarse más fuerte.",
            "La misericordia de Dios no tiene límites; la nuestra tampoco debería tenerlos.",
            "Reconocer el error es sabiduría; enmendarlo, virtud.",
            "Un corazón nuevo es posible, pero requiere dejar ir el viejo.",
            "Caminar en novedad de vida es elegir cada día no volver al pasado.",
            "Dios transforma el agua en vino, el dolor en gozo, la muerte en vida.",
            "El perdón es un acto de valentía, no de debilidad.",
            "La paz con el pasado es la puerta a la paz con el presente.",
            "Crecer a través del dolor es una de las formas más profundas de sanación.",
            "Solo Dios puede transformar un corazón, pero necesita tu permiso.",
            "La misericordia y el perdón son las alas que te llevan a la libertad.",
        ],
        "bendiciones": [
            "Que Zadkiel te enseñe a perdonar de corazón.",
            "Que la misericordia de Dios inunde tu vida.",
            "Que tu corazón endurecido se transforme en uno nuevo.",
            "Que tengas el valor de pedir perdón.",
            "Que la misericordia sea tu forma de amar.",
            "Que aprendas a perdonarte a ti mismo.",
            "Que la culpa se disipe y la paz te habite.",
            "Que tu espíritu se renueve cada día.",
            "Que dejes atrás el pasado con paz.",
            "Que cada día sea un nuevo comienzo para ti.",
            "Que el dolor se transforme en sabiduría.",
            "Que veas tu vida con ojos nuevos.",
            "Que las heridas del alma encuentren sanación.",
            "Que aceptes el perdón que Dios te ofrece.",
            "Que la humildad guíe tu camino.",
            "Que perdones sin condiciones.",
            "Que tus pensamientos se llenen de luz.",
            "Que vivas en la libertad de los hijos de Dios.",
            "Que tengas un corazón nuevo y renovado.",
            "Que sepas olvidar lo que debe olvidarse.",
            "Que tu vida sea transformada desde dentro.",
            "Que tengas fuerzas para levantarte después de caer.",
            "Que el valor no te falte para cambiar.",
            "Que camines en novedad de vida cada día.",
            "Que tus debilidades se transformen en fortalezas.",
            "Que perdones y sigas adelante con paz.",
            "Que tengas paz con tu pasado y tu presente.",
            "Que crezcas a través de cada dolor.",
            "Que tu corazón sea transformado por el amor divino.",
            "Que Zadkiel te guíe hacia la misericordia y el perdón.",
        ],
    },

    # ============================================
    # JOPHIEL — Belleza, pensamientos, inspiración
    # ============================================
    "jophiel": {
        "versiculos": [
            ("Y Jehová Dios plantó un huerto en Edén, al oriente; y puso allí al hombre.", "Génesis 2:8"),
            ("Los cielos cuentan la gloria de Dios, y el firmamento anuncia la obra de sus manos.", "Salmo 19:1"),
            ("¡Cuán hermosas son tus moradas, oh Jehová de los ejércitos!", "Salmo 84:1"),
            ("La hermosura es vana, y la belleza pasajera; mas la mujer que teme a Jehová, esa será alabada.", "Proverbios 31:30"),
            ("Cada cosa tiene su belleza, pero no todos pueden verla.", "Confucio (cita)"),
            ("Todo lo que es verdadero, todo lo honesto, todo lo justo, todo lo puro, en esto pensad.", "Filipenses 4:8"),
            ("Regocijaos en el Señor siempre. Y otra vez os digo: ¡Regocijaos!", "Filipenses 4:4"),
            ("El corazón alegre constituye buen remedio.", "Proverbios 17:22"),
            ("Alaben su nombre con danza; con pandero y arpa a él canten.", "Salmo 149:3"),
            ("Cantad a Jehová un cántico nuevo; cantad a Jehová, toda la tierra.", "Salmo 96:1"),
            ("La luz en las tinieblas resplandece, y las tinieblas no prevalecieron contra ella.", "Juan 1:5"),
            ("Vosotros sois la luz del mundo.", "Mateo 5:14"),
            ("Así alumbre vuestra luz delante de los hombres.", "Mateo 5:16"),
            ("Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.", "Eclesiastés 3:1"),
            ("Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios.", "Salmo 103:2"),
            ("En tu presencia hay plenitud de gozo.", "Salmo 16:11"),
            ("Me mostrarás la senda de la vida; en tu presencia hay plenitud de gozo.", "Salmo 16:11"),
            ("Deléitate asimismo en Jehová, y él te concederá las peticiones de tu corazón.", "Salmo 37:4"),
            ("Considerad los lirios del campo, cómo crecen.", "Mateo 6:28"),
            ("Toda buena dádiva y todo don perfecto descienden de lo alto.", "Santiago 1:17"),
            ("Grandes son las obras de Jehová, buscadas de todos los que las quieren.", "Salmo 111:2"),
            ("El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", "Salmo 91:1"),
            ("Dulce es la luz, y agradable a los ojos ver el sol.", "Eclesiastés 11:7"),
            ("Engrandece mi alma al Señor, y mi espíritu se regocija en Dios mi Salvador.", "Lucas 1:46-47"),
            ("La creación misma aguarda con ansiedad la revelación de los hijos de Dios.", "Romanos 8:19"),
            ("Encomienda a Jehová tus obras, y tus pensamientos serán afirmados.", "Proverbios 16:3"),
            ("El pensamiento del justo es rectitud.", "Proverbios 12:5"),
            ("Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida.", "Proverbios 4:23"),
            ("Porque cual es su pensamiento en su corazón, tal es él.", "Proverbios 23:7"),
            ("Renovaos en el espíritu de vuestra mente.", "Efesios 4:23"),
        ],
        "oraciones": [
            "Jophiel, muéstrame la belleza de la creación. Amén.",
            "Jophiel, enséñame a ver lo bello en lo simple. Amén.",
            "Jophiel, transforma mis pensamientos negativos. Amén.",
            "Jophiel, inspira mi creatividad y mis proyectos. Amén.",
            "Jophiel, ayúdame a ver la belleza en mí mismo. Amén.",
            "Jophiel, guíame a pensar en lo bueno y lo puro. Amén.",
            "Jophiel, trae armonía a mi vida y mi hogar. Amén.",
            "Jophiel, inspírame en el arte y la creación. Amén.",
            "Jophiel, enséñame a encontrar gozo en lo cotidiano. Amén.",
            "Jophiel, ayúdame a rodearme de belleza. Amén.",
            "Jophiel, transforma mis pensamientos oscuros en luz. Amén.",
            "Jophiel, inspira mis palabras y mis obras. Amén.",
            "Jophiel, ayúdame a cuidar mi mente y mi corazón. Amén.",
            "Jophiel, muéstrame la belleza del alma. Amén.",
            "Jophiel, inspira mi creatividad cada día. Amén.",
            "Jophiel, enséñame a pensar en lo bueno y lo justo. Amén.",
            "Jophiel, trae belleza y armonía a mi entorno. Amén.",
            "Jophiel, ayúdame a ver con ojos nuevos. Amén.",
            "Jophiel, inspira mis proyectos y sueños. Amén.",
            "Jophiel, ayúdame a cultivar la belleza interior. Amén.",
            "Jophiel, transforma mis pensamientos en oración. Amén.",
            "Jophiel, enséñame a apreciar lo que tengo. Amén.",
            "Jophiel, inspira a los artistas y creadores. Amén.",
            "Jophiel, ayúdame a encontrar la belleza en los demás. Amén.",
            "Jophiel, trae luz a mis pensamientos. Amém.",
            "Jophiel, guíame a pensar en lo noble y lo puro. Amén.",
            "Jophiel, inspira mi corazón y mi mente. Amén.",
            "Jophiel, enséñame a ver la belleza de Dios en todo. Amén.",
            "Jophiel, trae armonía a mis relaciones. Amén.",
            "Jophiel, inspírame a crear belleza en el mundo. Amén.",
        ],
        "reflexiones": [
            "La belleza está en los ojos de quien la busca con el corazón.",
            "Lo simple, lo pequeño, lo cotidiano: ahí habita mucha de la belleza de Dios.",
            "Tus pensamientos moldean tu realidad. Elige los que construyen.",
            "La creatividad es un reflejo del Creador en ti.",
            "Ver belleza en ti mismo es ver la obra de Dios.",
            "Pensar en lo bueno transforma la mente y el alma.",
            "La armonía exterior empieza por la armonía interior.",
            "Crear belleza es uno de los actos más profundos de amor.",
            "El gozo se esconde en los detalles que solemos ignorar.",
            "Rodearse de belleza no es superficial, es nutrir el alma.",
            "Los pensamientos oscuros se disipan con la luz del bien.",
            "Tus palabras pueden ser bellas o feas; elige las que construyen.",
            "Cuidar la mente es cuidar el corazón.",
            "La belleza del alma trasciende cualquier apariencia externa.",
            "La creatividad no es un don de unos pocos, es una invitación para todos.",
            "Pensar en lo justo y lo puro eleva el espíritu.",
            "La belleza que te rodea es un reflejo de la belleza que llevas dentro.",
            "Ver con ojos nuevos es aprender a maravillarse otra vez.",
            "Soñar y crear es participar de la obra de Dios en el mundo.",
            "La belleza interior se cultiva con paciencia y con amor.",
            "Cada pensamiento puede ser una oración si se eleva a lo alto.",
            "Apreciar lo que se tiene es el primer paso hacia la abundancia.",
            "El arte y la creación son ventanas al alma.",
            "Ver la belleza en los demás es reconocer la obra de Dios en ellos.",
            "La luz disipa las tinieblas; elige siempre la luz.",
            "Pensar en lo noble y lo puro transforma la vida.",
            "El corazón y la mente son jardines que hay que regar cada día.",
            "La belleza de Dios se refleja en toda su creación.",
            "La armonía en las relaciones es un arte que se aprende.",
            "Crear belleza en el mundo es una forma de oración.",
        ],
        "bendiciones": [
            "Que Jophiel te muestre la belleza de la creación.",
            "Que aprendas a ver lo bello en lo simple.",
            "Que tus pensamientos se transformen en luz.",
            "Que tu creatividad florezca cada día.",
            "Que veas la belleza que habita en ti.",
            "Que pienses en lo bueno, lo justo y lo puro.",
            "Que la armonía reine en tu vida y en tu hogar.",
            "Que el arte y la creación inspiren tu camino.",
            "Que encuentres gozo en lo cotidiano.",
            "Que tu entorno se llene de belleza.",
            "Que la luz disipe tus pensamientos oscuros.",
            "Que tus palabras y obras sean bellas.",
            "Que cuides tu mente y tu corazón con esmero.",
            "Que veas la belleza del alma en quienes te rodean.",
            "Que tu creatividad sea inspirada y fecunda.",
            "Que pienses siempre en lo bueno y lo justo.",
            "Que la belleza y la armonía te acompañen.",
            "Que veas tu vida con ojos nuevos.",
            "Que tus sueños y proyectos se hagan realidad.",
            "Que cultives la belleza interior cada día.",
            "Que tus pensamientos se eleven como oración.",
            "Que aprecies cada regalo que la vida te da.",
            "Que inspires a otros con tu arte y tu ejemplo.",
            "Que reconozcas la belleza en los demás.",
            "Que la luz guíe siempre tus pensamientos.",
            "Que pienses en lo noble y lo puro.",
            "Que tu corazón y tu mente estén en armonía.",
            "Que veas la belleza de Dios en todo lo creado.",
            "Que la armonía reine en tus relaciones.",
            "Que seas un creador de belleza en el mundo.",
        ],
    },
}

# ============================================
# GENERADOR DE SQL
# ============================================

def escapar_sql(texto):
    """Escapa comillas simples para SQL."""
    return texto.replace("'", "''")


def generar_sql():
    """Genera el archivo SQL con todo el contenido."""
    lineas = [
        "-- ============================================",
        "-- Contenido diario para 6 ángeles — 30 días cada uno",
        "-- Generado automáticamente por scripts/generar_contenido.py",
        "-- ============================================",
        "",
    ]
    
    total_angeles = 0
    total_piezas = 0
    
    for angel_slug, datos in CONTENIDO.items():
        lineas.append(f"-- ============================================")
        lineas.append(f"-- {angel_slug.upper()} — {DIAS} días")
        lineas.append(f"-- ============================================")
        lineas.append("")
        
        for i in range(DIAS):
            fecha = FECHA_INICIO + timedelta(days=i)
            versiculo, cita = datos["versiculos"][i]
            oracion = datos["oraciones"][i]
            reflexion = datos["reflexiones"][i]
            bendicion = datos["bendiciones"][i]
            
            lineas.append("INSERT INTO contenido_diario (angel_slug, fecha, versiculo, cita_versiculo, oracion, reflexion, bendicion, fecha_creacion)")
            lineas.append("VALUES (")
            lineas.append(f"  '{angel_slug}',")
            lineas.append(f"  '{fecha.isoformat()}',")
            lineas.append(f"  '{escapar_sql(versiculo)}',")
            lineas.append(f"  '{escapar_sql(cita)}',")
            lineas.append(f"  '{escapar_sql(oracion)}',")
            lineas.append(f"  '{escapar_sql(reflexion)}',")
            lineas.append(f"  '{escapar_sql(bendicion)}',")
            lineas.append(f"  strftime('%s', 'now')")
            lineas.append(");")
            lineas.append("")
            
            total_piezas += 1
        
        total_angeles += 1
    
    # Escribir el archivo
    ruta_salida = Path(__file__).parent.parent / "migrations" / "0006_contenido_otros_angeles.sql"
    ruta_salida.write_text("\n".join(lineas), encoding="utf-8")
    
    print(f"✅ Generado: {ruta_salida}")
    print(f"   Ángeles: {total_angeles}")
    print(f"   Piezas totales: {total_piezas}")
    print(f"   Rango de fechas: {FECHA_INICIO} → {FECHA_INICIO + timedelta(days=DIAS-1)}")


if __name__ == "__main__":
    generar_sql()