# -*- coding: utf-8 -*-
"""
Generador de contenido diario — TANDA 2 (días 31-60 del ciclo)
Genera 30 días de contenido nuevo para cada uno de los 7 ángeles.

Uso: python scripts/generar_contenido_tanda2.py
Salida: migrations/0009_contenido_tanda2.sql
"""

from datetime import date, timedelta
from pathlib import Path

# ============================================
# CONFIGURACIÓN
# ============================================

FECHA_INICIO = date(2026, 10, 23)  # Día 31 del ciclo (después de Tanda 1)
DIAS = 30

# ============================================
# CONTENIDO POR ÁNGEL
# ============================================

CONTENIDO = {
    "miguel": {    
        "versiculos": [
            ("Jehová es mi luz y mi salvación; ¿de quién temeré?", "Salmo 27:1"),
            ("Jehová es la fortaleza de mi vida; ¿de quién he de atemorizarme?", "Salmo 27:1"),
            ("Aunque un ejército acampe contra mí, no temerá mi corazón.", "Salmo 27:3"),
            ("Una cosa he demandado a Jehová, ésta buscaré: que esté yo en la casa de Jehová.", "Salmo 27:4"),
            ("Porque él me esconderá en su tabernáculo en el día del mal.", "Salmo 27:5"),
            ("Ahora levantará mi cabeza sobre mis enemigos que me rodean.", "Salmo 27:6"),
            ("Oye, oh Jehová, mi voz con que a ti clamo; ten misericordia de mí, y respóndeme.", "Salmo 27:7"),
            ("Mi corazón ha dicho de ti: Buscad mi rostro. Tu rostro buscaré, oh Jehová.", "Salmo 27:8"),
            ("No escondas tu rostro de mí; no deseches con ira a tu siervo.", "Salmo 27:9"),
            ("Aunque mi padre y mi madre me dejaran, con todo, Jehová me recogerá.", "Salmo 27:10"),
            ("Enséñame, oh Jehová, tu camino, y guíame por senda de rectitud.", "Salmo 27:11"),
            ("Creo que veré la bondad de Jehová en la tierra de los vivientes.", "Salmo 27:13"),
            ("Aguarda a Jehová; esfuérzate, y aliéntese tu corazón; sí, espera a Jehová.", "Salmo 27:14"),
            ("Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.", "Salmo 46:1"),
            ("Por tanto, no temeremos, aunque la tierra sea removida.", "Salmo 46:2"),
            ("Jehová de los ejércitos está con nosotros; nuestro refugio es el Dios de Jacob.", "Salmo 46:7"),
            ("Venid, ved las obras de Jehová, que ha puesto asolamientos en la tierra.", "Salmo 46:8"),
            ("Estad quietos, y conoced que yo soy Dios.", "Salmo 46:10"),
            ("Jehová de los ejércitos está con nosotros; nuestro refugio es el Dios de Jacob.", "Salmo 46:11"),
            ("Bendito sea Jehová, que nos ha sustentado y nos ha librado de todo mal.", "Salmo 68:19"),
            ("Jehová dará fuerza a su pueblo; Jehová bendecirá a su pueblo con paz.", "Salmo 29:11"),
            ("El ángel de Jehová acampa alrededor de los que le temen, y los defiende.", "Salmo 34:7"),
            ("Gustad, y ved que es bueno Jehová; dichoso el hombre que confía en él.", "Salmo 34:8"),
            ("Los ojos de Jehová están sobre los justos, y atentos sus oídos al clamor de ellos.", "Salmo 34:15"),
            ("Claman los justos, y Jehová oye, y los libra de todas sus angustias.", "Salmo 34:17"),
            ("Cercano está Jehová a los quebrantados de corazón.", "Salmo 34:18"),
            ("Muchas son las aflicciones del justo, pero de todas ellas le librará Jehová.", "Salmo 34:19"),
            ("Jehová redime el alma de sus siervos, y no serán condenados cuantos en él confían.", "Salmo 34:22"),
            ("Jehová, roca mía y castillo mío, y mi libertador.", "Salmo 18:2"),
            ("Invoqué a Jehová, quien es digno de ser alabado, y fui salvado de mis enemigos.", "Salmo 18:3"),
        ],
        "oraciones": [
            "San Miguel, sé mi amparo en los días de tormenta. Amén.",
            "San Miguel, defiéndeme de todo mal visible e invisible. Amén.",
            "San Miguel, dame fuerzas para levantarme cada mañana. Amén.",
            "San Miguel, protege a mi familia y a mis seres queridos. Amén.",
            "San Miguel, ayúdame a vencer mis miedos más profundos. Amén.",
            "San Miguel, sé mi escudo contra las tentaciones. Amén.",
            "San Miguel, guíame en la batalla espiritual de cada día. Amén.",
            "San Miguel, dame valentía para defender la verdad. Amén.",
            "San Miguel, protégeme en mis viajes y desplazamientos. Amén.",
            "San Miguel, ayúdame a discernir el bien del mal. Amén.",
            "San Miguel, sé mi compañero en la soledad. Amén.",
            "San Miguel, dame paz en medio de la incertidumbre. Amén.",
            "San Miguel, ayúdame a perdonar a quienes me han herido. Amén.",
            "San Miguel, protégeme del mal de ojo y las envidias. Amén.",
            "San Miguel, dame fortaleza en la enfermedad. Amén.",
            "San Miguel, sé mi apoyo en los momentos difíciles. Amén.",
            "San Miguel, ayúdame a confiar en la providencia divina. Amén.",
            "San Miguel, guárdame de los peligros del camino. Amén.",
            "San Miguel, dame serenidad ante las pruebas. Amén.",
            "San Miguel, protégeme de las malas influencias. Amén.",
            "San Miguel, ayúdame a ser valiente en la fe. Amén.",
            "San Miguel, sé mi defensor ante las injusticias. Amén.",
            "San Miguel, dame luz en las decisiones difíciles. Amén.",
            "San Miguel, protégeme en el trabajo y los estudios. Amén.",
            "San Miguel, ayúdame a mantener la calma en la adversidad. Amén.",
            "San Miguel, sé mi guardián durante la noche. Amén.",
            "San Miguel, dame fuerza para no rendirme. Amén.",
            "San Miguel, protégeme de todo daño físico y espiritual. Amén.",
            "San Miguel, ayúdame a caminar con esperanza. Amén.",
            "San Miguel, acompaña mi camino hoy y siempre. Amén.",
        ],
        "reflexiones": [
            "La protección de Dios no siempre significa ausencia de peligros, sino presencia en medio de ellos.",
            "Cuando sientas miedo, recuerda que Miguel está a tu lado, invisible pero real.",
            "La verdadera fortaleza no es no caer, sino levantarse cada vez que se cae.",
            "Dios no te pide que seas perfecto, te pide que confíes en Él.",
            "A veces la mayor batalla es la que se libra dentro de uno mismo. Miguel te ayuda a ganarla.",
            "El mal existe, pero no tiene la última palabra. La luz siempre vence.",
            "Confiar no es saber el final, es caminar con quien lo conoce.",
            "Cada día es una nueva oportunidad para vencer tus miedos con la ayuda del cielo.",
            "La oración es el arma más poderosa contra las fuerzas oscuras.",
            "Dios nunca te deja solo, aunque a veces no sientas su presencia.",
            "La protección divina no te exime de responsabilidad, te da fuerza para cumplirla.",
            "Los ángeles no siempre evitan los problemas, pero siempre están contigo en ellos.",
            "El coraje no es ausencia de miedo, es actuar a pesar del miedo.",
            "Cuando todo se derrumbe, afírmate en la roca que es Dios.",
            "La paz interior no depende de las circunstancias, sino de quién va contigo.",
            "A veces Dios permite las pruebas para mostrar su gloria en nosotros.",
            "La batalla espiritual se gana de rodillas, en oración.",
            "Miguel no pelea por ti, pelea contigo. Confía y actúa.",
            "El bien siempre encuentra el camino, aunque parezca oscuro.",
            "En la debilidad se manifiesta la fuerza de Dios.",
            "No estás solo en tu lucha. El cielo entero está contigo.",
            "La fe no elimina las tormentas, te da un ancla en medio de ellas.",
            "Dios no te promete una vida sin problemas, te promete su presencia constante.",
            "La victoria no siempre llega como esperamos, pero siempre llega.",
            "El miedo es una puerta; al otro lado está la libertad que Dios te da.",
            "A veces hay que dejar de luchar y dejar que Dios luche por nosotros.",
            "La protección más grande es saber que eres amado por Dios.",
            "Descansa. Miguel está velando mientras duermes.",
            "Confía en el proceso, aunque no entiendas el propósito.",
            "Dios está obrando incluso cuando todo parece perdido.",
        ],
        "bendiciones": [
            "Que la protección de San Miguel te envuelva hoy.",
            "Que los ángeles acampen alrededor de tu hogar.",
            "Que la fortaleza divina sostenga tus pasos.",
            "Que el valor llene tu corazón en las dificultades.",
            "Que Miguel aleje de ti todo mal y peligro.",
            "Que la paz de Dios guarde tu mente y tu corazón.",
            "Que tu fe se fortalezca con cada prueba superada.",
            "Que Miguel te defienda en las batallas invisibles.",
            "Que la confianza en Dios sea tu ancla firme.",
            "Que tu familia esté siempre custodiada por el cielo.",
            "Que los miedos se disipen ante la presencia divina.",
            "Que Miguel te acompañe en cada decisión importante.",
            "Que tu camino esté libre de peligros y tropiezos.",
            "Que la serenidad de Dios inunde tu alma.",
            "Que seas valiente incluso cuando todo esté en contra.",
            "Que los ángeles velen tu sueño cada noche.",
            "Que la protección divina te acompañe hoy y siempre.",
            "Que Miguel te enseñe a vencer con amor y no con violencia.",
            "Que tu corazón descanse en la fidelidad de Dios.",
            "Que las tormentas no te roben la paz interior.",
            "Que la justicia de Dios se manifieste en tu vida.",
            "Que los obstáculos se conviertan en oportunidades.",
            "Que la luz de Miguel ilumine tus momentos oscuros.",
            "Que tu hogar sea un refugio de paz y protección.",
            "Que la victoria del bien sea siempre tu victoria.",
            "Que Miguel te ayude a soltar lo que no puedes controlar.",
            "Que la presencia de Dios sea tu mayor seguridad.",
            "Que camines siempre bajo la sombra del Altísimo.",
            "Que tu fe sea más fuerte que tus miedos.",
            "Que Miguel te custodie hoy, mañana y siempre.",
        ],
    },
    "gabriel": {       
        "versiculos": [
            ("Entonces dijo María: He aquí la sierva del Señor; hágase conmigo conforme a tu palabra.", "Lucas 1:38"),
            ("Y el ángel le dijo: No temas, María, porque has hallado gracia delante de Dios.", "Lucas 1:30"),
            ("Y ahora, he aquí, serás mudo y no podrás hablar, hasta el día en que esto se haga.", "Lucas 1:20"),
            ("Respondiendo el ángel, le dijo: Yo soy Gabriel, que estoy delante de Dios.", "Lucas 1:19"),
            ("Y él vino a ella, y le dijo: ¡Alégrate, muy favorecida! El Señor es contigo.", "Lucas 1:28"),
            ("Y bendita tú entre las mujeres.", "Lucas 1:42"),
            ("Y sucedió que cuando Elisabeth oyó la salutación de María, la criatura saltó en su vientre.", "Lucas 1:41"),
            ("Porque ninguna cosa es imposible para Dios.", "Lucas 1:37"),
            ("Y dijo María: Engrandece mi alma al Señor.", "Lucas 1:46"),
            ("Y mi espíritu se regocija en Dios mi Salvador.", "Lucas 1:47"),
            ("Porque ha mirado la bajeza de su sierva; pues he aquí, desde ahora me dirán bienaventurada todas las generaciones.", "Lucas 1:48"),
            ("Porque me ha hecho grandes cosas el Poderoso; y santo es su nombre.", "Lucas 1:49"),
            ("Y su misericordia es de generación en generación a los que le temen.", "Lucas 1:50"),
            ("Hizo proezas con su brazo; esparció a los soberbios en el pensamiento de sus corazones.", "Lucas 1:51"),
            ("Quitó de los tronos a los poderosos, y exaltó a los humildes.", "Lucas 1:52"),
            ("A los hambrientos colmó de bienes, y a los ricos envió vacíos.", "Lucas 1:53"),
            ("Socorrió a Israel su siervo, acordándose de la misericordia.", "Lucas 1:54"),
            ("De la manera que habló a nuestros padres, a Abraham y a su descendencia para siempre.", "Lucas 1:55"),
            ("Y habló el ángel, y le dijo: El Espíritu Santo vendrá sobre ti.", "Lucas 1:35"),
            ("Y el poder del Altísimo te cubrirá con su sombra.", "Lucas 1:35"),
            ("Y entonces dieron voces alabando a Dios, y diciendo: Bendito el rey de Israel que viene en el nombre del Señor.", "Juan 12:13"),
            ("Envió su palabra, y los sanó, y los libró de su ruina.", "Salmo 107:20"),
            ("Toda palabra de Dios es limpia; él es escudo a los que en él esperan.", "Proverbios 30:5"),
            ("La exposición de tus palabras alumbra; hace entender a los simples.", "Salmo 119:130"),
            ("Lámpara es a mis pies tu palabra, y lumbre a mi camino.", "Salmo 119:105"),
            ("El cielo y la tierra pasarán, pero mis palabras no pasarán.", "Mateo 24:35"),
            ("Y conoceréis la verdad, y la verdad os hará libres.", "Juan 8:32"),
            ("Desead, como niños recién nacidos, la leche espiritual no adulterada.", "1 Pedro 2:2"),
            ("Y aquel Verbo fue hecho carne, y habitó entre nosotros.", "Juan 1:14"),
            ("La palabra de Cristo more en abundancia en vosotros.", "Colosenses 3:16"),
        ],
        "oraciones": [
            "San Gabriel, ayúdame a escuchar la voz de Dios con atención. Amén.",
            "San Gabriel, ayúdame a decir 'sí' como María dijo 'sí'. Amén.",
            "San Gabriel, mensajero divino, guíame en mis decisiones. Amén.",
            "San Gabriel, enséñame a proclamar con valentía la verdad. Amén.",
            "San Gabriel, ilumina mi mente para comprender las Escrituras. Amén.",
            "San Gabriel, ayúdame a llevar buenas noticias a los demás. Amén.",
            "San Gabriel, guárdame de las palabras vanas y dañinas. Amén.",
            "San Gabriel, enséñame a comunicar con amor. Amén.",
            "San Gabriel, ayúdame a escuchar antes de hablar. Amén.",
            "San Gabriel, guíame en el silencio cuando sea necesario. Amén.",
            "San Gabriel, dame claridad para entender la voluntad de Dios. Amén.",
            "San Gabriel, ayúdame a meditar la Palabra de Dios. Amén.",
            "San Gabriel, ilumina mi camino con la luz del Espíritu. Amén.",
            "San Gabriel, enséñame a compartir la fe con alegría. Amén.",
            "San Gabriel, ayúdame a ser luz para quienes me rodean. Amén.",
            "San Gabriel, protégeme de la mentira y el engaño. Amén.",
            "San Gabriel, ayúdame a caminar en la verdad. Amén.",
            "San Gabriel, enséñame a esperar con fe. Amén.",
            "San Gabriel, lleva mis plegarias al trono divino. Amén.",
            "San Gabriel, ayúdame a decir la verdad con caridad. Amén.",
            "San Gabriel, guíame en mis estudios y aprendizaje. Amén.",
            "San Gabriel, ayúdame a leer la Biblia con atención. Amén.",
            "San Gabriel, ilumina mi entendimiento en la confusión. Amén.",
            "San Gabriel, enséñame a escuchar a los demás. Amén.",
            "San Gabriel, ayúdame a discernir la voz de Dios. Amén.",
            "San Gabriel, guárdame de las malas conversaciones. Amén.",
            "San Gabriel, ayúdame a usar mis palabras para sanar. Amén.",
            "San Gabriel, enséñame a proclamar el Evangelio. Amén.",
            "San Gabriel, ayúdame a mantener la fe en tiempos difíciles. Amén.",
            "San Gabriel, guíame siempre hacia la verdad y el bien. Amén.",
        ],
        "reflexiones": [
            "A veces Dios habla en susurros. Gabriel te enseña a escuchar con el corazón abierto.",
            "El 'sí' de María cambió la historia. Tu 'sí' también puede cambiar la tuya.",
            "Las palabras construyen o destruyen. Elige siempre las que sanan.",
            "Dios no nos pide entenderlo todo, nos pide confiar en Él.",
            "El silencio no es vacío, es espacio donde Dios puede hablar.",
            "Escuchar es un acto de amor. Hoy, escucha más de lo que hablas.",
            "Compartir la fe no es imponer, es ofrecer con alegría.",
            "La verdad proclamada con amor transforma más que mil discursos vacíos.",
            "Cuando lees la Escritura, Dios te está hablando personalmente.",
            "La oración no es monólogo, es diálogo. Deja espacio para la respuesta.",
            "Un mensajero de Dios no busca ser escuchado, busca transmitir fielmente.",
            "Cada buena noticia que compartes es una semilla de esperanza.",
            "La claridad mental viene de la oración y el silencio.",
            "Ser luz no es brillar con luz propia, es dejar pasar la luz de Dios.",
            "Cuando no sepas qué decir, guarda silencio y ora.",
            "La Palabra de Dios es viva y eficaz, penetra hasta lo más profundo.",
            "A veces la mejor comunicación es el ejemplo, no las palabras.",
            "El Espíritu Santo te guía cuando le abres el corazón.",
            "La fe no se hereda, se elige cada día.",
            "Dios usa a los humildes para anunciar sus maravillas.",
            "Proclamar la verdad requiere valentía y prudencia.",
            "La esperanza es la certeza de que Dios cumple sus promesas.",
            "Cuando la duda te invada, vuelve a la Palabra.",
            "La revelación de Dios se da a quien la busca con humildad.",
            "Tu vida puede ser un evangelio vivo para otros.",
            "El mensajero no se glorifica a sí mismo, glorifica al que lo envía.",
            "Hablar menos y orar más suele ser el mejor consejo.",
            "La fe se fortalece al compartirla.",
            "Los planes de Dios son más grandes que los nuestros.",
            "El 'sí' a Dios es la puerta a la verdadera libertad.",
        ],
        "bendiciones": [
            "Que la claridad de San Gabriel ilumine tus decisiones.",
            "Que tu fe se fortalezca al escuchar la voz de Dios.",
            "Que seas portador de buenas noticias donde vayas.",
            "Que tus palabras sean bálsamo para quienes te escuchan.",
            "Que la luz del Espíritu Santo te guíe hoy.",
            "Que escuches más de lo que hablas y aprendas en el silencio.",
            "Que la Palabra de Dios more en tu corazón.",
            "Que tengas valentía para proclamar la verdad.",
            "Que el ángel Gabriel te acompañe en tus estudios.",
            "Que tu boca hable solo palabras que construyan.",
            "Que el silencio te regale la voz de Dios.",
            "Que la Escritura sea lámpara a tus pies.",
            "Que tu fe se comparta con alegría y sencillez.",
            "Que seas un testigo vivo del amor de Dios.",
            "Que la mentira no tenga poder sobre ti.",
            "Que puedas discernir la voz de Dios en medio del ruido.",
            "Que tus plegarias lleguen al trono de la gracia.",
            "Que el Espíritu Santo te ilumine en la confusión.",
            "Que tu mensaje sea siempre de esperanza.",
            "Que la verdad te haga libre y te mantenga firme.",
            "Que ilumines con tu ejemplo a quienes te rodean.",
            "Que la fe te sostenga en los momentos difíciles.",
            "Que el amor guíe cada palabra que pronuncies.",
            "Que seas un canal de las bendiciones de Dios.",
            "Que tu corazón esté abierto a escuchar al Señor.",
            "Que la Palabra transforme tu vida cada día.",
            "Que lleves esperanza a los que la han perdido.",
            "Que Dios te use para grandes cosas, como usó a María.",
            "Que el ángel de la anunciación te acompañe siempre.",
            "Que tu vida sea un anuncio vivo del Evangelio.",
        ],
    },
    "rafael": {
        "versiculos": [
            ("Yo soy Jehová tu sanador.", "Éxodo 15:26"),
            ("Sáname, oh Jehová, y seré sano; sálvame, y seré salvo.", "Jeremías 17:14"),
            ("El Señor sostiene al que tropieza y levanta al que está caído.", "Salmo 145:14"),
            ("Él sana a los quebrantados de corazón, y venda sus heridas.", "Salmo 147:3"),
            ("Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios.", "Salmo 103:2"),
            ("Él es quien perdona todas tus iniquidades, el que sana todas tus dolencias.", "Salmo 103:3"),
            ("Envió su palabra, y los sanó, y los libró de su ruina.", "Salmo 107:20"),
            ("Porque yo te restauraré y sanaré tus heridas, dice Jehová.", "Jeremías 30:17"),
            ("Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", "Mateo 11:28"),
            ("Y la oración de fe salvará al enfermo, y el Señor lo levantará.", "Santiago 5:15"),
            ("Jehová te guardará de todo mal; guardará tu alma.", "Salmo 121:7"),
            ("Jehová guardará tu salida y tu entrada desde ahora y para siempre.", "Salmo 121:8"),
            ("Alzaré mis ojos a los montes; ¿de dónde vendrá mi socorro?", "Salmo 121:1"),
            ("Mi socorro viene de Jehová, que hizo los cielos y la tierra.", "Salmo 121:2"),
            ("No dará tu pie al resbaladero, ni se dormirá el que te guarda.", "Salmo 121:3"),
            ("He aquí, no se dormirá ni dormitará el que guarda a Israel.", "Salmo 121:4"),
            ("Jehová es tu guardador; Jehová es tu sombra a tu mano derecha.", "Salmo 121:5"),
            ("El sol no te fatigará de día, ni la luna de noche.", "Salmo 121:6"),
            ("El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", "Salmo 91:1"),
            ("Diré yo a Jehová: Esperanza mía, y castillo mío; mi Dios, en quien confiaré.", "Salmo 91:2"),
            ("Porque él te librará del lazo del cazador, de la peste destructora.", "Salmo 91:3"),
            ("Con sus plumas te cubrirá, y debajo de sus alas estarás seguro.", "Salmo 91:4"),
            ("Escudo y adarga es su verdad.", "Salmo 91:4"),
            ("No temerás el terror nocturno, ni saeta que vuele de día.", "Salmo 91:5"),
            ("Ni pestilencia que ande en oscuridad, ni mortandad que en medio del día destruya.", "Salmo 91:6"),
            ("Caerán a tu lado mil, y diez mil a tu diestra; mas a ti no llegará.", "Salmo 91:7"),
            ("Porque a sus ángeles mandará acerca de ti, que te guarden en todos tus caminos.", "Salmo 91:11"),
            ("En las manos te llevarán, para que tu pie no tropiece en piedra.", "Salmo 91:12"),
            ("Sobre el león y el áspid pisarás; hollarás al cachorro del león y al dragón.", "Salmo 91:13"),
            ("Por cuanto en mí ha puesto su amor, yo también lo libraré.", "Salmo 91:14"),
        ],
        "oraciones": [
            "San Rafael, medicina de Dios, sáname en cuerpo, alma y espíritu. Amén.",
            "San Rafael, alivia mis dolencias y renueva mis fuerzas. Amén.",
            "San Rafael, acompaña a los enfermos y consuela sus corazones. Amén.",
            "San Rafael, protege mi hogar y mis bienes. Amén.",
            "San Rafael, guía mis viajes y desplazamientos. Amén.",
            "San Rafael, acompaña a los viajeros y peregrinos. Amén.",
            "San Rafael, protege mi matrimonio y mi familia. Amén.",
            "San Rafael, sana las heridas emocionales de mi alma. Amén.",
            "San Rafael, ayúdame a aceptar lo que no puedo cambiar. Amén.",
            "San Rafael, dame paciencia en la enfermedad. Amén.",
            "San Rafael, restaura mi salud y mi esperanza. Amén.",
            "San Rafael, ayúdame a confiar en la providencia. Amén.",
            "San Rafael, sé mi compañero en la soledad. Amén.",
            "San Rafael, cuida a mis seres queridos enfermos. Amén.",
            "San Rafael, alivia el dolor de quienes sufren. Amén.",
            "San Rafael, sana las relaciones rotas. Amén.",
            "San Rafael, trae paz a mi familia. Amén.",
            "San Rafael, ayúdame a perdonar y a pedir perdón. Amén.",
            "San Rafael, dame sabiduría para cuidar mi cuerpo. Amén.",
            "San Rafael, enséñame a descansar en Dios. Amén.",
            "San Rafael, protégeme de todo peligro. Amén.",
            "San Rafael, guárdame en el camino de la vida. Amén.",
            "San Rafael, consuela a los que lloran. Amén.",
            "San Rafael, fortalece mi fe en la prueba. Amén.",
            "San Rafael, ayúdame a ser instrumento de sanación. Amén.",
            "San Rafael, ilumina a los médicos y enfermeros. Amén.",
            "San Rafael, dame serenidad ante la incertidumbre. Amén.",
            "San Rafael, alivia mi ansiedad y mis angustias. Amén.",
            "San Rafael, guárdame de todo mal. Amén.",
            "San Rafael, acompáñame hoy y siempre. Amén.",
        ],
        "reflexiones": [
            "La sanación no siempre es física. A veces Dios sana primero el alma.",
            "El dolor no es el final, es una puerta a algo nuevo que Dios está gestando.",
            "Acompañar al que sufre es una de las formas más puras de amor.",
            "Aceptar lo que no podemos cambiar es el primer paso hacia la paz.",
            "La salud es un regalo; cuidarla es un acto de gratitud.",
            "En cada camino, Dios envía ángeles que te guardan. Confía.",
            "La enfermedad puede ser maestra de humildad y paciencia.",
            "El descanso no es debilidad, es confianza en que Dios sostiene.",
            "El dolor compartido pesa menos. Busca compañía en la prueba.",
            "Dios no siempre sana como queremos, pero siempre sana lo que necesitamos.",
            "El sufrimiento no es castigo, es misterio que solo Dios comprende.",
            "La paciencia en la enfermedad es una forma de oración.",
            "Los ángeles no siempre evitan la enfermedad, pero siempre acompañan.",
            "Un corazón agradecido sana más rápido que mil medicinas.",
            "El cuidado del cuerpo es también un acto espiritual.",
            "Cuando no puedas dormir, ora. Los ángeles velan contigo.",
            "La sanación empieza por aceptar la realidad tal como es.",
            "Confiar en Dios no exime de ir al médico. Ambos van de la mano.",
            "El amor es la medicina más poderosa que existe.",
            "A veces la mayor sanación es aprender a vivir con lo que no se puede curar.",
            "La oración de los demás sostiene cuando las propias fuerzas fallan.",
            "El dolor presente no anula las bendiciones pasadas.",
            "Dios sana a través de personas: médicos, amigos, familiares.",
            "La fe no elimina el dolor, le da sentido.",
            "Descansar es confiar en que Dios sigue trabajando mientras dormimos.",
            "La salud recuperada es una segunda oportunidad.",
            "El cuerpo enfermo puede albergar un alma sana.",
            "Los ángeles también sanan el corazón, no solo el cuerpo.",
            "La gratitud es bálsamo para el alma.",
            "Dios siempre sana, aunque a veces sea de otra manera a la esperada.",
        ],
        "bendiciones": [
            "Que la sanación de San Rafael llegue a tu cuerpo y alma.",
            "Que San Rafael acompañe cada paso de tu camino.",
            "Que la bendición de San Rafael proteja tu hogar.",
            "Que la salud y la paz sean tus compañeras hoy.",
            "Que San Rafael consuele todo dolor que lleves dentro.",
            "Que aceptes con paz lo que no puedes cambiar.",
            "Que la salud florezca en ti como un regalo divino.",
            "Que los ángeles te guarden en todos tus caminos.",
            "Que en la enfermedad o en la salud, Dios te sostenga.",
            "Que el descanso repare tus fuerzas y tu alma.",
            "Que tus seres queridos estén siempre custodiados.",
            "Que la protección divina te envuelva hoy.",
            "Que San Rafael guíe tus viajes y tus pasos.",
            "Que tu hogar sea un refugio de paz y amor.",
            "Que la providencia divina sostenga cada día tu vida.",
            "Que en lo desconocido encuentres la cercanía de Dios.",
            "Que la serenidad te acompañe en la incertidumbre.",
            "Que cuides tu cuerpo como templo del Espíritu.",
            "Que las heridas del pasado sanen con el tiempo.",
            "Que la enfermedad no te robe la esperanza.",
            "Que tu matrimonio sea bendecido y fortalecido.",
            "Que el amor una lo que estaba dividido.",
            "Que el amor por los tuyos crezca cada día.",
            "Que aprendas a amar como Dios te ama a ti.",
            "Que el perdón libere tu corazón de toda carga.",
            "Que la paz reine en tu familia y en tu hogar.",
            "Que el vínculo del amor sea siempre tu fortaleza.",
            "Que lleves con amor las cargas de los demás.",
            "Que tus consuelos sean bálsamo para quien llora.",
            "Que San Rafael te guarde y guíe a los que amas.",
        ],
    },
    "uriel": {
        "versiculos": [
            ("Lámpara es a mis pies tu palabra, y lumbre a mi camino.", "Salmo 119:105"),
            ("El principio de la sabiduría es el temor de Jehová.", "Proverbios 9:10"),
            ("Si alguno tiene falta de sabiduría, pídala a Dios, el cual da a todos abundantemente.", "Santiago 1:5"),
            ("En el entendimiento del hombre está la fuente de la vida.", "Proverbios 16:22"),
            ("La exposición de tus palabras alumbra; hace entender a los simples.", "Salmo 119:130"),
            ("Dame entendimiento, y guardaré tu ley, y la cumpliré de todo corazón.", "Salmo 119:34"),
            ("El que adquiere entendimiento ama su alma.", "Proverbios 19:8"),
            ("Mas la sabiduría que es de lo alto es primeramente pura, después pacífica.", "Santiago 3:17"),
            ("El corazón del entendido adquiere sabiduría.", "Proverbios 18:15"),
            ("Porque Jehová da la sabiduría, y de su boca viene el conocimiento.", "Proverbios 2:6"),
            ("Mejor es adquirir sabiduría que oro preciado.", "Proverbios 16:16"),
            ("Bienaventurado el hombre que halla la sabiduría.", "Proverbios 3:13"),
            ("El entendido en la palabra hallará el bien.", "Proverbios 16:20"),
            ("La sabiduría es lo primero; adquiere sabiduría.", "Proverbios 4:7"),
            ("El que anda con sabios, sabio será.", "Proverbios 13:20"),
            ("Andad como hijos de luz, porque el fruto del Espíritu es en toda bondad.", "Efesios 5:8-9"),
            ("Vosotros sois la luz del mundo.", "Mateo 5:14"),
            ("Así alumbre vuestra luz delante de los hombres.", "Mateo 5:16"),
            ("Dios es luz, y no hay ningunas tinieblas en él.", "1 Juan 1:5"),
            ("Todo lo que es verdadero, todo lo honesto, todo lo justo, en esto pensad.", "Filipenses 4:8"),
            ("Escudriñad las Escrituras; porque a vosotros os parece que en ellas tenéis la vida eterna.", "Juan 5:39"),
            ("Y conoceréis la verdad, y la verdad os hará libres.", "Juan 8:32"),
            ("La palabra de Cristo more en abundancia en vosotros.", "Colosenses 3:16"),
            ("Toda Escritura es inspirada por Dios, y útil para enseñar.", "2 Timoteo 3:16"),
            ("Porque la palabra de Dios es viva y eficaz.", "Hebreos 4:12"),
            ("Desead, como niños recién nacidos, la leche espiritual no adulterada.", "1 Pedro 2:2"),
            ("El cielo y la tierra pasarán, pero mis palabras no pasarán.", "Mateo 24:35"),
            ("Y aquel Verbo fue hecho carne, y habitó entre nosotros.", "Juan 1:14"),
            ("En él estaba la vida, y la vida era la luz de los hombres.", "Juan 1:4"),
            ("La luz en las tinieblas resplandece, y las tinieblas no prevalecieron contra ella.", "Juan 1:5"),
        ],
        "oraciones": [
            "Uriel, luz divina, ilumina mi mente y mi entendimiento. Amén.",
            "Uriel, guíame en el camino del conocimiento y la verdad. Amén.",
            "Uriel, ayúdame a estudiar con dedicación y sabiduría. Amén.",
            "Uriel, inspira mis pensamientos y mis proyectos. Amén.",
            "Uriel, ilumina las decisiones que debo tomar hoy. Amén.",
            "Uriel, ayúdame a buscar la verdad con humildad. Amén.",
            "Uriel, dame sabiduría para entender las Escrituras. Amén.",
            "Uriel, guíame en el estudio de tu Palabra. Amén.",
            "Uriel, ilumina mi mente en la confusión. Amén.",
            "Uriel, ayúdame a discernir lo verdadero de lo falso. Amén.",
            "Uriel, enséñame a pensar en lo bueno y lo justo. Amén.",
            "Uriel, guíame a la verdad que libera. Amén.",
            "Uriel, ilumina mi camino en la oscuridad. Amén.",
            "Uriel, ayúdame a aprender con alegría. Amén.",
            "Uriel, dame paciencia en el estudio y la investigación. Amén.",
            "Uriel, inspira mis palabras cuando enseño. Amén.",
            "Uriel, ayúdame a comprender la voluntad de Dios. Amén.",
            "Uriel, ilumina mi corazón para amar la verdad. Amén.",
            "Uriel, guíame al conocimiento que acerca a Dios. Amén.",
            "Uriel, ayúdame a crecer en sabiduría cada día. Amén.",
            "Uriel, ilumina mi entendimiento con tu luz. Amén.",
            "Uriel, enséñame a escuchar antes de juzgar. Amén.",
            "Uriel, guíame a la humildad intelectual. Amén.",
            "Uriel, ayúdame a reconocer mis limitaciones. Amén.",
            "Uriel, ilumina mi mente para servir mejor. Amén.",
            "Uriel, ayúdame a usar el conocimiento para el bien. Amén.",
            "Uriel, guíame a la verdad que transforma. Amén.",
            "Uriel, ilumina mis decisiones cotidianas. Amén.",
            "Uriel, enséñame a aprender de mis errores. Amén.",
            "Uriel, guíame siempre hacia la luz de Dios. Amén.",
        ],
        "reflexiones": [
            "La verdadera sabiduría empieza por reconocer cuánto no sabemos todavía.",
            "La luz de Dios ilumina los rincones más oscuros de nuestra mente.",
            "Estudiar es un acto de amor cuando se hace para servir mejor.",
            "Los pensamientos buenos son semillas de acciones buenas.",
            "Cada decisión iluminada por la fe es un paso hacia la plenitud.",
            "Buscar la verdad con humildad es más sabio que creer tenerla toda.",
            "Las Escrituras son un pozo sin fondo del que siempre se puede sacar agua nueva.",
            "En la confusión, la oración es la brújula que orienta.",
            "Discernir no es adivinar, es escuchar con atención y orar con paciencia.",
            "Pensar en lo bueno, lo justo y lo verdadero transforma la mente.",
            "La verdad que libera no siempre es cómoda, pero siempre es liberadora.",
            "En la oscuridad, incluso una pequeña luz marca la diferencia.",
            "Aprender con alegría es uno de los mayores regalos que puedes darte.",
            "La paciencia en el estudio es una forma de respeto hacia el conocimiento.",
            "Enseñar bien es un acto de generosidad y de humildad.",
            "Comprender la voluntad de Dios es un camino, no un destino.",
            "Amar la verdad es amar a Dios, porque Él es la Verdad.",
            "Todo conocimiento que acerca a Dios es conocimiento que vale la pena.",
            "Crecer en sabiduría es crecer en humanidad.",
            "La luz de Dios disipa toda oscuridad, si se la dejamos entrar.",
            "Escuchar antes de juzgar es uno de los gestos más sabios.",
            "La humildad intelectual es reconocer que siempre hay más por aprender.",
            "Conocer nuestros límites es el primer paso para superarlos.",
            "El conocimiento que no sirve al bien, no es verdadero conocimiento.",
            "Usar lo que sabes para ayudar a otros es sabiduría en acción.",
            "La verdad que transforma no es la que se acumula, sino la que se vive.",
            "Las decisiones pequeñas también merecen luz y discernimiento.",
            "Equivocarse es parte del aprendizaje; levantarse, parte del crecimiento.",
            "Caminar hacia la luz es caminar hacia Dios.",
            "La verdadera luz no deslumbra, ilumina con serenidad.",
        ],
        "bendiciones": [
            "Que la luz de Uriel ilumine tu mente y tu camino.",
            "Que la sabiduría de lo alto guíe tus decisiones.",
            "Que el estudio sea fuente de alegría y crecimiento.",
            "Que la inspiración de Uriel anime tus proyectos.",
            "Que ilumine tus decisiones y disipe tus dudas.",
            "Que busques la verdad con humildad y perseverancia.",
            "Que las Escrituras iluminen cada día tu vida.",
            "Que el estudio de la Palabra te transforme.",
            "Que en la confusión encuentres la luz de Dios.",
            "Que disciernas con claridad lo verdadero de lo falso.",
            "Que tus pensamientos se eleven a lo bueno y lo justo.",
            "Que la verdad de Dios te haga libre.",
            "Que la luz de Uriel disipe tus tinieblas.",
            "Que aprendas con alegría y enseñes con generosidad.",
            "Que la paciencia sea tu compañera en el estudio.",
            "Que tus enseñanzas inspiren a otros.",
            "Que comprendas la voluntad de Dios para tu vida.",
            "Que tu corazón ame la verdad cada día más.",
            "Que el conocimiento te acerque a Dios.",
            "Que crezcas en sabiduría y en gracia.",
            "Que la luz de Uriel ilumine tu entendimiento.",
            "Que sepas escuchar antes de juzgar.",
            "Que la humildad guíe tu camino intelectual.",
            "Que reconozcas tus límites con paz.",
            "Que tu mente iluminada sirva al bien común.",
            "Que uses el conocimiento para el bien de los demás.",
            "Que la verdad transforme tu vida desde dentro.",
            "Que ilumines cada decisión con discernimiento.",
            "Que aprendas de cada error y sigas creciendo.",
            "Que Uriel te guíe siempre hacia la luz de Dios.",
        ],
    },
    "chamuel": {
        "versiculos": [
            ("La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da.", "Juan 14:27"),
            ("No se turbe vuestro corazón, ni tenga miedo.", "Juan 14:27"),
            ("Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones.", "Filipenses 4:7"),
            ("Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios.", "Mateo 5:9"),
            ("Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad.", "Gálatas 5:22"),
            ("Seguid la paz con todos, y la santidad, sin la cual nadie verá al Señor.", "Hebreos 12:14"),
            ("Porque Dios no es Dios de confusión, sino de paz.", "1 Corintios 14:33"),
            ("En paz me acostaré, y asimismo dormiré; porque solo tú, Jehová, me haces vivir confiado.", "Salmo 4:8"),
            ("Mucha paz tienen los que aman tu ley, y no hay para ellos tropiezo.", "Salmo 119:165"),
            ("La misericordia y la verdad se encontraron; la justicia y la paz se besaron.", "Salmo 85:10"),
            ("Amarás a tu prójimo como a ti mismo.", "Mateo 22:39"),
            ("Un mandamiento nuevo os doy: Que os améis unos a otros.", "Juan 13:34"),
            ("El amor es sufrido, es benigno; el amor no tiene envidia.", "1 Corintios 13:4"),
            ("Sobre todo, vestíos de amor, que es el vínculo perfecto.", "Colosenses 3:14"),
            ("Amados, amémonos unos a otros; porque el amor es de Dios.", "1 Juan 4:7"),
            ("Nosotros le amamos a él, porque él nos amó primero.", "1 Juan 4:19"),
            ("Buscad la paz, y seguidla.", "1 Pedro 3:11"),
            ("Si es posible, en cuanto dependa de vosotros, estad en paz con todos.", "Romanos 12:18"),
            ("El que ama a su hermano, permanece en la luz.", "1 Juan 2:10"),
            ("Bienaventurados los que buscan la paz y la procuran.", "Proverbios 12:20"),
            ("Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros.", "Efesios 4:32"),
            ("No os ha sobrevenido ninguna tentación que no sea humana.", "1 Corintios 10:13"),
            ("Buscad, y hallaréis; llamad, y se os abrirá.", "Mateo 7:7"),
            ("Porque todo aquel que pide, recibe; y el que busca, halla.", "Mateo 7:8"),
            ("Jehová es mi pastor; nada me faltará.", "Salmo 23:1"),
            ("Esforzaos, y él fortalecerá vuestro corazón, todos los que esperáis en Jehová.", "Salmo 31:24"),
            ("Cercano está Jehová a todos los que le invocan de veras.", "Salmo 145:18"),
            ("Encomienda a Jehová tu camino, y confía en él; y él hará.", "Salmo 37:5"),
            ("El corazón alegre constituye buen remedio.", "Proverbios 17:22"),
            ("Regocijaos en el Señor siempre. Y otra vez os digo: ¡Regocijaos!", "Filipenses 4:4"),
        ],
        "oraciones": [
            "Chamuel, trae paz a mi corazón y a mi mente. Amén.",
            "Chamuel, ayúdame a amar como Dios me ama. Amén.",
            "Chamuel, enséñame a perdonar de corazón. Amén.",
            "Chamuel, trae serenidad a mis días agitados. Amén.",
            "Chamuel, ayúdame a encontrar lo que he perdido. Amén.",
            "Chamuel, guíame hacia las personas que necesitan paz. Amén.",
            "Chamuel, dame tu paz en medio de la tormenta. Amén.",
            "Chamuel, sana las relaciones rotas en mi vida. Amén.",
            "Chamuel, ayúdame a ser un pacificador. Amén.",
            "Chamuel, trae armonía a mi hogar. Amén.",
            "Chamuel, enséñame a amar sin condiciones. Amén.",
            "Chamuel, ayúdame a dejar atrás el rencor. Amén.",
            "Chamuel, dame paz cuando la ansiedad me invade. Amén.",
            "Chamuel, guíame a la reconciliación. Amén.",
            "Chamuel, trae paz a mis pensamientos. Amén.",
            "Chamuel, ayúdame a buscar la paz y seguirla. Amén.",
            "Chamuel, dame serenidad ante las dificultades. Amén.",
            "Chamuel, ayúdame a amar a quien me cuesta amar. Amén.",
            "Chamuel, sana mi corazón herido. Amén.",
            "Chamuel, trae paz a las naciones y al mundo. Amén.",
            "Chamuel, ayúdame a encontrar el gozo en lo simple. Amén.",
            "Chamuel, guíame en la búsqueda de lo que anhelo. Amén.",
            "Chamuel, ayúdame a confiar en el tiempo de Dios. Amén.",
            "Chamuel, trae esperanza a mi vida. Amén.",
            "Chamuel, dame paz en la espera. Amén.",
            "Chamuel, ayúdame a vivir en paz con todos. Amén.",
            "Chamuel, enséñame a perdonarme a mí mismo. Amén.",
            "Chamuel, trae reconciliación a mi familia. Amén.",
            "Chamuel, ayúdame a encontrar la paz interior. Amén.",
            "Chamuel, guíame siempre hacia el amor y la paz. Amén.",
        ],
        "reflexiones": [
            "La paz no es ausencia de problemas, sino presencia de Dios en medio de ellos.",
            "El amor verdadero se demuestra en lo cotidiano, no solo en lo extraordinario.",
            "Perdonar no es olvidar, es soltar el peso que te ata al pasado.",
            "La serenidad no viene de fuera, viene de dentro. Cultívala cada día.",
            "A veces lo que perdemos nos prepara para encontrar algo mejor.",
            "Ser pacificador no es evitar conflictos, es resolverlos con amor.",
            "La paz empieza en tu interior y se refleja en lo exterior.",
            "Las relaciones rotas pueden sanar con paciencia y perdón.",
            "El amor sin condiciones es el más puro y el más transformador.",
            "Soltar el rencor es un regalo que te haces a ti mismo.",
            "La ansiedad se calma cuando dejamos de intentar controlarlo todo.",
            "Reconciliarse es un acto de valentía y de humildad.",
            "Los pensamientos en paz generan días en paz.",
            "Buscar la paz es una decisión diaria, no un estado permanente.",
            "La serenidad ante las dificultades es señal de fe madura.",
            "Amar a quien nos cuesta amar es el mayor acto de libertad.",
            "El corazón herido puede sanar; el tiempo y el amor son medicina.",
            "La paz del mundo empieza por la paz de cada corazón.",
            "El gozo está en las cosas simples; solo hay que aprender a verlo.",
            "Buscar con fe es encontrar con sorpresa.",
            "El tiempo de Dios no es el nuestro, pero siempre es el mejor.",
            "La esperanza es la luz que ilumina incluso la noche más oscura.",
            "En la espera, Dios trabaja silenciosamente a nuestro favor.",
            "Vivir en paz con todos es un proyecto de toda la vida.",
            "Perdonarse a uno mismo es tan importante como perdonar a otros.",
            "La reconciliación familiar es un regalo que trasciende generaciones.",
            "La paz interior es un tesoro que nadie te puede arrebatar.",
            "El amor y la paz son las alas del alma.",
            "Cuando buscas la paz, la encuentras; cuando la siembras, florece.",
            "El camino del amor es el camino de la paz.",
        ],
        "bendiciones": [
            "Que la paz de Chamuel inunde tu corazón.",
            "Que aprendas a amar como Dios te ama.",
            "Que el perdón libere tu alma de toda carga.",
            "Que la serenidad te acompañe en cada día.",
            "Que encuentres lo que tu corazón busca.",
            "Que seas instrumento de paz donde vayas.",
            "Que la paz de Dios guarde tu mente y corazón.",
            "Que las relaciones rotas sanen en tu vida.",
            "Que seas un pacificador en tu entorno.",
            "Que la armonía reine en tu hogar.",
            "Que ames sin condiciones y sin medida.",
            "Que dejes atrás el rencor y abraces la paz.",
            "Que la ansiedad se disipe ante la presencia de Dios.",
            "Que la reconciliación sea posible en tu vida.",
            "Que tus pensamientos estén en paz.",
            "Que busques y sigas siempre la paz.",
            "Que la serenidad sea tu compañera en las dificultades.",
            "Que ames incluso a quien te cuesta amar.",
            "Que tu corazón herido encuentre sanación.",
            "Que la paz reine en tu entorno y en el mundo.",
            "Que el gozo de lo simple llene tus días.",
            "Que encuentres lo que anhelas con fe y paciencia.",
            "Que confíes en el tiempo perfecto de Dios.",
            "Que la esperanza ilumine tu camino.",
            "Que la paz te sostenga en la espera.",
            "Que vivas en paz con todos y contigo mismo.",
            "Que aprendas a perdonarte y a seguir adelante.",
            "Que la reconciliación llegue a tu familia.",
            "Que la paz interior sea tu fuerza cada día.",
            "Que Chamuel te guíe siempre hacia el amor y la paz.",
        ],
    },
    "zadkiel": {
        "versiculos": [
            ("Jehová es misericordioso y piadoso; tardo para la ira, y grande en misericordia.", "Salmo 145:8"),
            ("Como el padre se compadece de sus hijos, se compadece Jehová de los que le temen.", "Salmo 103:13"),
            ("Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros.", "Efesios 4:32"),
            ("Porque si perdonáis a los hombres sus ofensas, os perdonará también a vosotros vuestro Padre celestial.", "Mateo 6:14"),
            ("Y cuando estéis orando, perdonad, si tenéis algo contra alguno.", "Marcos 11:25"),
            ("De manera que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron.", "2 Corintios 5:17"),
            ("He aquí que yo hago cosa nueva; pronto saldrá a luz; ¿no la conoceréis?", "Isaías 43:19"),
            ("Echad de vosotros todas vuestras transgresiones con que habéis pecado.", "Ezequiel 18:31"),
            ("Lávame más y más de mi maldad, y límpiame de mi pecado.", "Salmo 51:2"),
            ("Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.", "Salmo 51:10"),
            ("Vuélvete a mí, y yo me volveré a ti.", "Malaquías 3:7"),
            ("Desecha todas tus transgresiones, y hazte un corazón nuevo.", "Ezequiel 18:31"),
            ("Jehová está cerca de los quebrantados de corazón.", "Salmo 34:18"),
            ("No te acordarás de las cosas anteriores, ni las traerás a la memoria.", "Isaías 65:17"),
            ("Yo, yo soy el que borro tus rebeliones por amor de mí mismo.", "Isaías 43:25"),
            ("Sáname, oh Jehová, y seré sano; sálvame, y seré salvo.", "Jeremías 17:14"),
            ("Porque yo sé los pensamientos que tengo acerca de vosotros, pensamientos de paz.", "Jeremías 29:11"),
            ("El amor cubrirá multitud de pecados.", "1 Pedro 4:8"),
            ("Porque yo perdonaré sus iniquidades, y nunca más me acordaré de sus pecados.", "Jeremías 31:34"),
            ("Nunca más se acordará el pecado ni la iniquidad.", "Hebreos 10:17"),
            ("Confesaos vuestras ofensas unos a otros, y orad unos por otros.", "Santiago 5:16"),
            ("Si confesamos nuestros pecados, él es fiel y justo para perdonar.", "1 Juan 1:9"),
            ("Todos pecaron, y están destituidos de la gloria de Dios.", "Romanos 3:23"),
            ("Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros.", "Romanos 5:8"),
            ("Y todo lo que antes era ganancia, lo tengo por basura, a fin de ganar a Cristo.", "Filipenses 3:7-8"),
            ("Olvidando ciertamente lo que queda atrás, y extendiéndome a lo que está delante.", "Filipenses 3:13"),
            ("Consideraos muertos al pecado, pero vivos para Dios en Cristo Jesús.", "Romanos 6:11"),
            ("De modo que ya no eres esclavo, sino hijo.", "Gálatas 4:7"),
            ("La misericordia y la verdad se encontraron; la justicia y la paz se besaron.", "Salmo 85:10"),
            ("Bienaventurados los misericordiosos, porque ellos alcanzarán misericordia.", "Mateo 5:7"),
        ],
        "oraciones": [
            "Zadkiel, enséñame a perdonar como Dios me perdona. Amén.",
            "Zadkiel, ayúdame a soltar el rencor y el resentimiento. Amén.",
            "Zadkiel, transforma mi corazón endurecido. Amén.",
            "Zadkiel, ayúdame a pedir perdón a quien he ofendido. Amén.",
            "Zadkiel, dame un corazón misericordioso. Amén.",
            "Zadkiel, ayúdame a perdonarme a mí mismo. Amén.",
            "Zadkiel, límpiame de toda culpa y remordimiento. Amén.",
            "Zadkiel, renueva mi espíritu y mi mente. Amén.",
            "Zadkiel, ayúdame a dejar atrás el pasado. Amén.",
            "Zadkiel, dame fuerzas para comenzar de nuevo. Amén.",
            "Zadkiel, transforma mi dolor en aprendizaje. Amén.",
            "Zadkiel, ayúdame a ver con ojos nuevos. Amén.",
            "Zadkiel, sana las heridas de mi alma. Amén.",
            "Zadkiel, ayúdame a aceptar el perdón de Dios. Amén.",
            "Zadkiel, dame humildad para reconocer mis errores. Amén.",
            "Zadkiel, ayúdame a perdonar sin condiciones. Amén.",
            "Zadkiel, transforma mis pensamientos negativos. Amén.",
            "Zadkiel, ayúdame a vivir en la libertad de los hijos de Dios. Amén.",
            "Zadkiel, dame un corazón nuevo y un espíritu renovado. Amén.",
            "Zadkiel, ayúdame a olvidar lo que debe ser olvidado. Amén.",
            "Zadkiel, transforma mi vida desde dentro. Amén.",
            "Zadkiel, ayúdame a levantarme después de caer. Amén.",
            "Zadkiel, dame valor para cambiar. Amén.",
            "Zadkiel, ayúdame a caminar en novedad de vida. Amén.",
            "Zadkiel, transforma mis debilidades en fortalezas. Amén.",
            "Zadkiel, ayúdame a perdonar y a seguir adelante. Amén.",
            "Zadkiel, dame paz con mi pasado. Amén.",
            "Zadkiel, ayúdame a crecer a través del dolor. Amén.",
            "Zadkiel, transforma mi corazón como solo Dios puede. Amén.",
            "Zadkiel, guíame siempre hacia la misericordia y el perdón. Amén.",
        ],
        "reflexiones": [
            "El perdón no cambia el pasado, pero sí cambia el futuro.",
            "Perdonar no es decir que estuvo bien, es liberarte del peso del rencor.",
            "La misericordia es un regalo que se multiplica cuando se comparte.",
            "Transformarse no es cambiar de piel, es cambiar de corazón.",
            "Dios no se cansa de perdonar; nosotros no deberíamos cansarnos de pedir perdón.",
            "El pasado no puede cambiarse, pero sí puede soltarse.",
            "La culpa que te atormenta no viene de Dios; Él perdona sin condiciones.",
            "Reconocer los errores es el primer paso de la transformación.",
            "Cuando perdonas, liberas a dos: al otro y a ti mismo.",
            "La misericordia no es debilidad, es la fuerza más poderosa del universo.",
            "Cada nuevo día es una oportunidad para empezar de nuevo.",
            "Dios ve en ti lo que puedes llegar a ser, no solo lo que has sido.",
            "Transformarse duele a veces, pero siempre vale la pena.",
            "El corazón endurecido se ablanda con el calor del amor divino.",
            "Perdonarse a sí mismo es un acto de humildad y de fe.",
            "La verdadera libertad se encuentra al soltar el rencor.",
            "Dios no recuerda tus pecados una vez perdonados. ¿Por qué los recuerdas tú?",
            "La transformación empieza en lo pequeño y se extiende a lo grande.",
            "El dolor puede ser maestro de sabiduría si se vive con fe.",
            "Cada caída es una oportunidad para levantarse más fuerte.",
            "La misericordia de Dios no tiene límites; la nuestra tampoco debería tenerlos.",
            "Reconocer el error es sabiduría; enmendarlo, virtud.",
            "Un corazón nuevo es posible, pero requiere dejar ir el viejo.",
            "Caminar en novedad de vida es elegir cada día no volver al pasado.",
            "Dios transforma el agua en vino, el dolor en gozo, la muerte en vida.",
            "El perdón es un acto de valentía, no de debilidad.",
            "La paz con el pasado es la puerta a la paz con el presente.",
            "Crecer a través del dolor es una de las formas más profundas de sanación.",
            "Solo Dios puede transformar un corazón, pero necesita tu permiso.",
            "La misericordia y el perdón son las alas que te llevan a la libertad.",
        ],
        "bendiciones": [
            "Que Zadkiel te enseñe a perdonar de corazón.",
            "Que la misericordia de Dios inunde tu vida.",
            "Que tu corazón endurecido se transforme en uno nuevo.",
            "Que tengas el valor de pedir perdón.",
            "Que la misericordia sea tu forma de amar.",
            "Que aprendas a perdonarte a ti mismo.",
            "Que la culpa se disipe y la paz te habite.",
            "Que tu espíritu se renueve cada día.",
            "Que dejes atrás el pasado con paz.",
            "Que cada día sea un nuevo comienzo para ti.",
            "Que el dolor se transforme en sabiduría.",
            "Que veas tu vida con ojos nuevos.",
            "Que las heridas del alma encuentren sanación.",
            "Que aceptes el perdón que Dios te ofrece.",
            "Que la humildad guíe tu camino.",
            "Que perdones sin condiciones.",
            "Que tus pensamientos se llenen de luz.",
            "Que vivas en la libertad de los hijos de Dios.",
            "Que tengas un corazón nuevo y renovado.",
            "Que sepas olvidar lo que debe olvidarse.",
            "Que tu vida sea transformada desde dentro.",
            "Que tengas fuerzas para levantarte después de caer.",
            "Que el valor no te falte para cambiar.",
            "Que camines en novedad de vida cada día.",
            "Que tus debilidades se transformen en fortalezas.",
            "Que perdones y sigas adelante con paz.",
            "Que tengas paz con tu pasado y tu presente.",
            "Que crezcas a través de cada dolor.",
            "Que tu corazón sea transformado por el amor divino.",
            "Que Zadkiel te guíe hacia la misericordia y el perdón.",
        ],
    },
    "jophiel": {
        "versiculos": [
            ("Y Jehová Dios plantó un huerto en Edén, al oriente; y puso allí al hombre.", "Génesis 2:8"),
            ("Los cielos cuentan la gloria de Dios, y el firmamento anuncia la obra de sus manos.", "Salmo 19:1"),
            ("¡Cuán hermosas son tus moradas, oh Jehová de los ejércitos!", "Salmo 84:1"),
            ("La hermosura es vana, y la belleza pasajera; mas la mujer que teme a Jehová, esa será alabada.", "Proverbios 31:30"),
            ("Todo lo que es verdadero, todo lo honesto, todo lo justo, todo lo puro, en esto pensad.", "Filipenses 4:8"),
            ("Regocijaos en el Señor siempre. Y otra vez os digo: ¡Regocijaos!", "Filipenses 4:4"),
            ("El corazón alegre constituye buen remedio.", "Proverbios 17:22"),
            ("Alaben su nombre con danza; con pandero y arpa a él canten.", "Salmo 149:3"),
            ("Cantad a Jehová un cántico nuevo; cantad a Jehová, toda la tierra.", "Salmo 96:1"),
            ("La luz en las tinieblas resplandece, y las tinieblas no prevalecieron contra ella.", "Juan 1:5"),
            ("Vosotros sois la luz del mundo.", "Mateo 5:14"),
            ("Así alumbre vuestra luz delante de los hombres.", "Mateo 5:16"),
            ("Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.", "Eclesiastés 3:1"),
            ("Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios.", "Salmo 103:2"),
            ("En tu presencia hay plenitud de gozo.", "Salmo 16:11"),
            ("Me mostrarás la senda de la vida; en tu presencia hay plenitud de gozo.", "Salmo 16:11"),
            ("Deléitate asimismo en Jehová, y él te concederá las peticiones de tu corazón.", "Salmo 37:4"),
            ("Considerad los lirios del campo, cómo crecen.", "Mateo 6:28"),
            ("Toda buena dádiva y todo don perfecto descienden de lo alto.", "Santiago 1:17"),
            ("Grandes son las obras de Jehová, buscadas de todos los que las quieren.", "Salmo 111:2"),
            ("El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", "Salmo 91:1"),
            ("Dulce es la luz, y agradable a los ojos ver el sol.", "Eclesiastés 11:7"),
            ("Engrandece mi alma al Señor, y mi espíritu se regocija en Dios mi Salvador.", "Lucas 1:46-47"),
            ("La creación misma aguarda con ansiedad la revelación de los hijos de Dios.", "Romanos 8:19"),
            ("Encomienda a Jehová tus obras, y tus pensamientos serán afirmados.", "Proverbios 16:3"),
            ("El pensamiento del justo es rectitud.", "Proverbios 12:5"),
            ("Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida.", "Proverbios 4:23"),
            ("Porque cual es su pensamiento en su corazón, tal es él.", "Proverbios 23:7"),
            ("Renovaos en el espíritu de vuestra mente.", "Efesios 4:23"),
            ("Y no os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento.", "Romanos 12:2"),
        ],
        "oraciones": [
            "Jophiel, muéstrame la belleza de la creación. Amén.",
            "Jophiel, enséñame a ver lo bello en lo simple. Amén.",
            "Jophiel, transforma mis pensamientos negativos. Amén.",
            "Jophiel, inspira mi creatividad y mis proyectos. Amén.",
            "Jophiel, ayúdame a ver la belleza en mí mismo. Amén.",
            "Jophiel, guíame a pensar en lo bueno y lo puro. Amén.",
            "Jophiel, trae armonía a mi vida y mi hogar. Amén.",
            "Jophiel, inspírame en el arte y la creación. Amén.",
            "Jophiel, enséñame a encontrar gozo en lo cotidiano. Amén.",
            "Jophiel, ayúdame a rodearme de belleza. Amén.",
            "Jophiel, transforma mis pensamientos oscuros en luz. Amén.",
            "Jophiel, inspira mis palabras y mis obras. Amén.",
            "Jophiel, ayúdame a cuidar mi mente y mi corazón. Amén.",
            "Jophiel, muéstrame la belleza del alma. Amén.",
            "Jophiel, inspira mi creatividad cada día. Amén.",
            "Jophiel, enséñame a pensar en lo bueno y lo justo. Amén.",
            "Jophiel, trae belleza y armonía a mi entorno. Amén.",
            "Jophiel, ayúdame a ver con ojos nuevos. Amén.",
            "Jophiel, inspira mis proyectos y sueños. Amén.",
            "Jophiel, ayúdame a cultivar la belleza interior. Amén.",
            "Jophiel, transforma mis pensamientos en oración. Amén.",
            "Jophiel, enséñame a apreciar lo que tengo. Amén.",
            "Jophiel, inspira a los artistas y creadores. Amén.",
            "Jophiel, ayúdame a encontrar la belleza en los demás. Amén.",
            "Jophiel, trae luz a mis pensamientos. Amén.",
            "Jophiel, guíame a pensar en lo noble y lo puro. Amén.",
            "Jophiel, inspira mi corazón y mi mente. Amén.",
            "Jophiel, enséñame a ver la belleza de Dios en todo. Amén.",
            "Jophiel, trae armonía a mis relaciones. Amén.",
            "Jophiel, inspírame a crear belleza en el mundo. Amén.",
        ],
        "reflexiones": [
            "La belleza está en los ojos de quien la busca con el corazón.",
            "Lo simple, lo pequeño, lo cotidiano: ahí habita mucha de la belleza de Dios.",
            "Tus pensamientos moldean tu realidad. Elige los que construyen.",
            "La creatividad es un reflejo del Creador en ti.",
            "Ver belleza en ti mismo es ver la obra de Dios.",
            "Pensar en lo bueno transforma la mente y el alma.",
            "La armonía exterior empieza por la armonía interior.",
            "Crear belleza es uno de los actos más profundos de amor.",
            "El gozo se esconde en los detalles que solemos ignorar.",
            "Rodearse de belleza no es superficial, es nutrir el alma.",
            "Los pensamientos oscuros se disipan con la luz del bien.",
            "Tus palabras pueden ser bellas o feas; elige las que construyen.",
            "Cuidar la mente es cuidar el corazón.",
            "La belleza del alma trasciende cualquier apariencia externa.",
            "La creatividad no es un don de unos pocos, es una invitación para todos.",
            "Pensar en lo justo y lo puro eleva el espíritu.",
            "La belleza que te rodea es un reflejo de la belleza que llevas dentro.",
            "Ver con ojos nuevos es aprender a maravillarse otra vez.",
            "Soñar y crear es participar de la obra de Dios en el mundo.",
            "La belleza interior se cultiva con paciencia y con amor.",
            "Cada pensamiento puede ser una oración si se eleva a lo alto.",
            "Apreciar lo que se tiene es el primer paso hacia la abundancia.",
            "El arte y la creación son ventanas al alma.",
            "Ver la belleza en los demás es reconocer la obra de Dios en ellos.",
            "La luz disipa las tinieblas; elige siempre la luz.",
            "Pensar en lo noble y lo puro transforma la vida.",
            "El corazón y la mente son jardines que hay que regar cada día.",
            "La belleza de Dios se refleja en toda su creación.",
            "La armonía en las relaciones es un arte que se aprende.",
            "Crear belleza en el mundo es una forma de oración.",
        ],
        "bendiciones": [
            "Que Jophiel te muestre la belleza de la creación.",
            "Que aprendas a ver lo bello en lo simple.",
            "Que tus pensamientos se transformen en luz.",
            "Que tu creatividad florezca cada día.",
            "Que veas la belleza que habita en ti.",
            "Que pienses en lo bueno, lo justo y lo puro.",
            "Que la armonía reine en tu vida y en tu hogar.",
            "Que el arte y la creación inspiren tu camino.",
            "Que encuentres gozo en lo cotidiano.",
            "Que tu entorno se llene de belleza.",
            "Que la luz disipe tus pensamientos oscuros.",
            "Que tus palabras y obras sean bellas.",
            "Que cuides tu mente y tu corazón con esmero.",
            "Que veas la belleza del alma en quienes te rodean.",
            "Que tu creatividad sea inspirada y fecunda.",
            "Que pienses siempre en lo bueno y lo justo.",
            "Que la belleza y la armonía te acompañen.",
            "Que veas tu vida con ojos nuevos.",
            "Que tus sueños y proyectos se hagan realidad.",
            "Que cultives la belleza interior cada día.",
            "Que tus pensamientos se eleven como oración.",
            "Que aprecies cada regalo que la vida te da.",
            "Que inspires a otros con tu arte y tu ejemplo.",
            "Que reconozcas la belleza en los demás.",
            "Que la luz guíe siempre tus pensamientos.",
            "Que pienses en lo noble y lo puro.",
            "Que tu corazón y tu mente estén en armonía.",
            "Que veas la belleza de Dios en todo lo creado.",
            "Que la armonía reine en tus relaciones.",
            "Que seas un creador de belleza en el mundo.",
        ],
    },
}
# ============================================
# GENERADOR DE SQL
# ============================================

def escapar_sql(texto):
    """Escapa comillas simples para SQL."""
    return texto.replace("'", "''")


def generar_sql():
    """Genera el archivo SQL con todo el contenido de la Tanda 2."""
    lineas = [
        "-- ============================================",
        "-- TANDA 2 — Contenido diario (días 31-60 del ciclo)",
        "-- Generado automáticamente por scripts/generar_contenido_tanda2.py",
        "-- 7 ángeles × 30 días = 210 piezas",
        "-- ============================================",
        "",
    ]

    total_angeles = 0
    total_piezas = 0

    for angel_slug, datos in CONTENIDO.items():
        lineas.append(f"-- ============================================")
        lineas.append(f"-- {angel_slug.upper()} — 30 días")
        lineas.append(f"-- ============================================")
        lineas.append("")

        for i in range(DIAS):
            fecha = FECHA_INICIO + timedelta(days=i)
            versiculo, cita = datos["versiculos"][i]
            oracion = datos["oraciones"][i]
            reflexion = datos["reflexiones"][i]
            bendicion = datos["bendiciones"][i]

            # dia_ciclo = 31 + i (días 31-60)
            dia_ciclo = 31 + i

            lineas.append("INSERT INTO contenido_diario (angel_slug, fecha, dia_ciclo, versiculo, cita_versiculo, oracion, reflexion, bendicion, fecha_creacion)")
            lineas.append("VALUES (")
            lineas.append(f"  '{angel_slug}',")
            lineas.append(f"  '{fecha.isoformat()}',")
            lineas.append(f"  {dia_ciclo},")
            lineas.append(f"  '{escapar_sql(versiculo)}',")
            lineas.append(f"  '{escapar_sql(cita)}',")
            lineas.append(f"  '{escapar_sql(oracion)}',")
            lineas.append(f"  '{escapar_sql(reflexion)}',")
            lineas.append(f"  '{escapar_sql(bendicion)}',")
            lineas.append(f"  strftime('%s', 'now')")
            lineas.append(");")
            lineas.append("")

            total_piezas += 1

        total_angeles += 1

    # Escribir el archivo
    ruta_salida = Path(__file__).parent.parent / "migrations" / "0009_contenido_tanda2.sql"
    ruta_salida.write_text("\n".join(lineas), encoding="utf-8")

    print(f"✅ Generado: {ruta_salida}")
    print(f"   Ángeles: {total_angeles}")
    print(f"   Piezas totales: {total_piezas}")
    print(f"   Rango de fechas: {FECHA_INICIO} → {FECHA_INICIO + timedelta(days=DIAS-1)}")
    print(f"   Días del ciclo: 31 → 60")


if __name__ == "__main__":
    generar_sql()